### ISSUE TITLE
Prevent duplicates when adding a song to a playlist

### ISSUE THREAD

**Issue by denysvitali** [spotify/web-api#413] opened 2017-01-29 00:03 UTC
In [Add Tracks to a Playlist](https://developer.spotify.com/web-api/add-tracks-to-playlist/) enpoint description the ability to add a track only if it isn't a duplicate is not available / not documented.

It would be nice to have a query parameter such as "prevent_duplicate" that when set to 1 / true it doesn't add the track if another one is already present.

In alternative to this, a new endpoint "Is song in playlist?" would be nice. At the moment, the only way to prevent a duplicate is to go through the whole playlist by using the [Get a Playlist’s Tracks](https://developer.spotify.com/web-api/get-playlists-tracks/) endpoint. This method returns a playlist track object, that contains a (full!) track object.
I can imagine that in your end such a query requires more processing than a simple track id listing, plus the method is limited to 100 entries, thus searching for a duplicate on big playlists may require more than a single request.

**Comment by hughrawlinson** [comment] 2017-01-29 11:07
Hey @denysvitali - thanks for the feature requests, well consider them! :)

**Comment by tal** [comment] 2017-02-21 02:41
Another solution would be to easily get every playlist of yours a particular song is in. I doubt the data is indexed that way, but would also allow to solve such problems.

**Comment by hughrawlinson** [comment] 2017-03-20 17:53
I've realised this issue is a duplicate of #118, so I'll close it as a duplicate. Please subscribe there for any updates! Thanks for reporting the issue.

**Closed by hughrawlinson** 2017-03-20 17:53 UTC
Labels: feature request
