### ISSUE TITLE
Player is_playing always returns true

### ISSUE THREAD

**Issue by gillesbergerp** [spotify/web-api#623] opened 2017-07-26 06:42 UTC
Player is_playing always returns true

Issue found on July 26th 2017..

#### Endpoint(s):
* `GET /v1/me/player`

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get Information About The User's Current Playback`

#### Expected behaviour:
Information about current users playback with `is_playing` returning false, when no music is being played at the moment

#### Actual behaviour:
Information about current users playback - `is_playing` returns true although no music is being played.

**Comment by arirawr** [comment] 2017-07-27 08:50
Hi @gillesbergerp - I'm not able to replicate this issue. Is it still occurring?

**Comment by gillesbergerp** [comment] 2017-07-27 11:12
This seems to happen sporadically... Yesterday I had this problem again - but only for a short amount of time. Afterwards everything worked fine again. 
Remarkably, both times it occurred, all Spotify Connect devices that are linked to my test account were turned off. So, it was virtually impossible that music was playing.

**Comment by bih** [comment] 2017-08-01 09:58
Hi @gillesbergerp,

Sorry to hear you were having issues with the `is_playing` flag in the API. Unfortunately there isn't much progress we can make if we cannot reproduce the steps, but because it seems like a potential bug, we'll keep this open.

Hope that you're not having problems anymore with the endpoint!

**Comment by tance77** [comment] 2017-08-04 06:39
I can confirm this. I'm having the same issue. When closing Spotify completely on my computer this endpoint still says 
```
is_playing: true
```
The progress_ms still counts up as well as if it were playing, but when you re-open Spotify it returns to where it last left off.

**Comment by gLarsVegas** [comment] 2017-08-05 12:41
I can definitely confirm this issue. Unfortunately, I have no idea what causes it because it only occurs sporadically. Sometimes is_playing will just not be updated for hours. I saw that phenomenon often in the log of my scrobbler and a lot of people complained about tracks being scrobbled like 300 times. Since I couldnt reproduce it, I just stopped using is_playing.

I guess it's about closing the client (or switching between connect devices?) as others have already suggested.

**Comment by tdhooper** [comment] 2017-08-09 10:48
Maybe related https://github.com/spotify/web-api/issues/499

**Comment by artechventure** [comment] 2018-03-16 11:11
I have the same issue. I'm getting is_playing true while I'm not playing, and items not updated

**Comment by bih** [comment] 2018-07-27 12:57
Hey folks!

We have taken a look at this, and unfortunately have not been able to replicate it. If I stop playing, the API returns `is_playing: false` and if I suddenly shut down my device, the API does not return a response.

Given that this has not received engagement for some time, I'm going to assume this issue is resolved. If this is not the case, please feel free to comment or open a new issue and reference so we can re-investigate this issue!

Cheers 👍

**Closed by bih** 2018-07-27 12:57 UTC
Labels: bug
