### ISSUE TITLE
Have Spotify want to support to play full length of tracks?

### ISSUE THREAD

**Issue by Englbach** [spotify/web-api#65] opened 2015-06-06 06:28 UTC
Have Spotify want to support to play full length of tracks?. Now. Just support on android and IOS. I don't like.

**Comment by JMPerez** [comment] 2015-06-06 07:54
@Englbach this is a duplicate of your previous issue https://github.com/spotify/web-api/issues/64

**Closed by JMPerez** 2015-06-06 07:54 UTC

**Comment by ekennedy80** [comment] 2017-12-10 00:52
So is Spotify going to add the full length of track feature ever?
