### ISSUE TITLE
[All mediums] - The ability to "add to top of Que" would be really helpful

### ISSUE THREAD

**Issue by jar122head** [spotify/web-api#237] opened 2016-05-26 18:18 UTC
The ability to add a song to the top or the bottom of the que would be a really amazing feature.

**Comment by JohnnyCrazy** [comment] 2016-05-26 20:06
Duplicate of #15 @jar122head

**Comment by thelinmichael** [comment] 2016-05-29 09:12
As @JohnnyCrazy stated, this is a duplicate of #15.

**Closed by thelinmichael** 2016-05-29 09:12 UTC
