### ISSUE TITLE
Bug: Added songs are not played, when playlist is started via web api

### ISSUE THREAD

**Issue by Kaiser1989** [spotify/web-api#783] opened 2018-02-07 21:32 UTC
Issue found on February 19th 2015.

#### Endpoint(s):
PUT https://api.spotify.com/v1/me/player/play
POST https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks

#### Scope(s):
user-modify-playback-state
playlist-modify-public
playlist-modify-private

#### Steps to reproduce:
1. Create Playlist with 2 tracks. 
2. Start playlist via endpoint with "me/player/play". 
3. When second song is playing, add new song to playlist with "users/{user_id}/playlists/{playlist_id}/tracks". 

#### Expected behaviour:
Added song should be played after second song ends, as it is added to playlist after the current playing song. 

#### Actual behaviour:
Added song is not played after second song ends. Instead a suggested song is played.

#### Strange behaviour:
The song is played correctly, if the playlist is started via spotify desktop app, and then added to the list. This only happens if the playlist is started via api.

#### Addtional Information:
This error occures since about one week. Before everything was working fine

**Comment by arirawr** [comment] 2018-02-09 12:25
Hi @Kaiser1989 - thanks for the report!

This seems like a duplicate of #537. I'm going to close this issue and you can follow that one for updates.

**Closed by arirawr** 2018-02-09 12:25 UTC
