### ISSUE TITLE
Cloud API method [v1/me/player/play] times out?

### ISSUE THREAD

**Issue by ConradConnect** [spotify/web-api#927] opened 2018-06-27 09:41 UTC
By using v1/me/player/play method with e.g. Amazon Echo or Google Home only works if the speaker device was recently used with Spotify. 

This means that if I start a playlist on the speaker device directly via Alexa, then I have to chance to Start / Pause / Resume the playlist via the cloud API. But if I stop the streaming and I wait around 1 hour, then I will not be able to start the playlist again via the API. First i need to trigger the playlist again "manually"...

Is there a way to overcome this issue? Can we somehow "wake up" the device to be able to start a playlist anytime via the cloud API?

**Comment by bih** [comment] 2018-06-27 10:07
Hi @ConradConnect,

Integrations with third-party hardware can operate slightly differently at times, so "waking up" varies on the device and the operating system. I can't comment too much on that as that is device-specific and not specific to the Web API.

However, we have received reports of this before. I suggest looking at the [Get a User's Available Devices](https://developer.spotify.com/console/get-users-available-devices/) endpoint and specifying in the play command the `device_id` as a temporary workaround.

As I'm understanding this as a duplicate of #924, I'm going to close this issue. Please comment on that particular ticket and subscribe for updates. Of course, feel free to re-open if you feel it is not a duplicate and I can look into it further.

Cheers!

**Closed by bih** 2018-06-27 10:07 UTC

**Comment by ConradConnect** [comment] 2018-07-02 06:52
Hi there,
One further question: do you have any device tested on your side that can wake up or does not go to stand-by at all? Or is there a list somewhere which shows the "compatible" devices?
Thank you!
