### ISSUE TITLE
Search endpoints return 404 Not Found if query contains the slash '/' character

### ISSUE THREAD

**Issue by ClemensSchneider** [spotify/web-api#187] opened 2016-03-22 05:47 UTC
We stumbled across an issue when using the slash `/` character in the query-part of the search endpoint (searching for the album _The 20/20 Experience - The Complete Experience)_:

https://developer.spotify.com/web-api/console/get-search-item/?q=The+20%2F20+Experience+-+The+Complete+Experience&type=album

The response is a `HTTP 404` which is not expected to indicate that there are no results. It seems that a `404` is used to indicate an error during search (compare to an empty result https://developer.spotify.com/web-api/console/get-search-item/?q=qwertzzzzz&type=album)

The characters that are not valid in a search query should be documented so people are able to strip them from the query.

**Comment by mikesnare** [comment] 2016-03-24 17:46
This used to work, so I'm not sure if it's an intentional exclusion that needs documentation or just a regression that should be fixed (and I'd argue it's the latter).

One query in particular that has worked for a while but is now broken is https://api.spotify.com/v1/search?q=De%2FVision&type=artist, which should match https://play.spotify.com/artist/1bN9idF4rgIhaaKFpwgzoQ (De/Vision).  I've had to update code to replace slashes with spaces so the query is now https://api.spotify.com/v1/search?q=De+Vision&type=artist, but that's incorrect, since it would allow for "De Vision" (if they existed) to be the better match when the intent was De/Vision.

**Comment by jsimonsson** [comment] 2016-04-06 07:20
Thank you for your patience, this issue is now solved.

**Closed by jsimonsson** 2016-04-06 07:20 UTC
Labels: bug, search
