### ISSUE TITLE
Category list is missing "TV & Movies"

### ISSUE THREAD

**Issue by michaelherger** [spotify/web-api#880] opened 2018-05-15 20:47 UTC
Issue found on May 15th 2018.

#### Endpoint(s):
* `https://api.spotify.com/v1/browse/categories`

#### Steps to reproduce:
1. Open the API Console
2. Call the `categories ` endpoint with `country` `CH` or `DE`

#### Expected behaviour:
Spotify Desktop or mobile app would list a category "TV und Filme" (TV and Movies), but the API does not.

#### Actual behaviour:
Category "TV und Filme" is missing.

Probably a dupe of #577

**Comment by arirawr** [comment] 2018-08-27 09:48
Closing this as a duplicate of #577. Please follow that issue for updates!

**Closed by arirawr** 2018-08-27 09:48 UTC
