### ISSUE TITLE
Problem when searching a song

### ISSUE THREAD

**Issue by mcvicious** [spotify/web-api#411] opened 2017-01-25 02:04 UTC
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET api.spotify.com/v1/search

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Search the track named veterinauta
#### Expected behaviour:
When i search in the app browser, got a song, but when i search in API console, don't have results. I proved change the market but nothing.

**Comment by hughrawlinson** [comment] 2017-01-26 10:31
That looks like a bug! Thanks for reporting it, I've passed it on to the responsible team. I'll update you here when it's resolved.

**Comment by hughrawlinson** [comment] 2017-03-20 16:46
Hey @mcvicious - that song isn't appearing in search either in the API or the app browser now, so I can't reproduce the issue. I'll close it for now, but if you find another song with this issue please let me know.

**Closed by hughrawlinson** 2017-03-20 16:46 UTC
Labels: bug
