### ISSUE TITLE
add sort filter tags

### ISSUE THREAD

**Issue by CyrusZei** [spotify/web-api#1064] opened 2018-10-21 12:07 UTC
Issue found on October 21th 2018.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/search?q=year:2004&type=track&popularity=100

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call https://api.spotify.com/v1/search?q=year:2004&type=track&popularity=100

#### Expected behaviour:
I want it to be sorted by popularity and I dont want to make 2.000 calls and then sort it myself.

#### Actual behaviour:
It filter out the popularity parameter.

**Comment by CyrusZei** [comment] 2018-12-05 17:41
any updates on this ?

**Comment by bih** [comment] 2018-12-28 17:34
Hello,

This is a duplicate of #1066 and I asked for some more information on use cases. As a result, I'll go and close this and we can continue the discussion on the other ticket.

**Closed by bih** 2018-12-28 17:34 UTC
