### ISSUE TITLE
playlist endpoint does not correctly populate `offset` field in response

### ISSUE THREAD

**Issue by spikegrobstein** [spotify/web-api#152] opened 2015-12-31 23:57 UTC
When making the following request:

    GET /v1/users/${USER}/playlists/${PLAYLIST_ID}/tracks?offset=100&limit=100

The response populates the `offset` field with a `0` rather than `100` as would be expected.

When I try to fetch a large playlist in a loop, I use those fields to create new URIs to fetch more items from the playlist, which causes my app to get into an infinite loop.

The other playlist tracks endpoint (`/v1/users/${USER}/playlists/${PLAYLIST_ID}/tracks`) does set the `offset` field correctly, but doesn't include other metadata about the playlist that I use.

In the interim, I'm working around this by parsing out the `next` field, which contains the full URL for the next page of items, but having this fixed would be ideal.

thanks!

**Comment by thelinmichael** [comment] 2016-10-16 10:25
Can't reproduce this issue using the [Get Playlist's Tracks](https://developer.spotify.com/web-api/console/get-playlist-tracks/) endpoint. The response contains `offset`, but it's set to `100` in the `previous` attribute, which is correct. If you're however referring to the [Get Playlist](https://developer.spotify.com/web-api/console/get-playlist/#complete) endpoint, it doesn't make sense to use `offset` since it _should_ return the first page of the tracks in the playlist. If you want to know more about the tracks, your application needs to use the Get Playlist's Tracks endpoint. 

I'm closing this issue. If you @spikegrobstein, or anyone else, is experiencing this issue again, please feel free to reopen it.

**Closed by thelinmichael** 2016-10-16 10:25 UTC
Labels: bug

**Comment by napstr** [comment] 2017-03-09 18:48
I stumbled upon this, because I was experiencing a similar issue.

The problem was on my end, I solved it by calling the `.parameter(name, value)` function of my request builder instead of adding `?offset=100&limit=100` to the url path directly, which the builder wasn't processing properly.

Hope this helps anyone else ending up here :)
