### ISSUE TITLE
Changing privacy of a playlist

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#343] opened 2016-11-07 22:53 UTC
Hi,
It seems there is an issue for changing privacy (public/private) of a playlist by this way => https://developer.spotify.com/web-api/change-playlist-details

That's not working for me, don't get any error but the privacy not changing... Could you please check if there's no issue with that ?
I had good scopes, and doing the same request for the rename wich working great.

**Comment by jstlnd** [comment] 2016-11-08 08:39
Hi @blackarcanis,
Thanks for your report! This indeed seems to have broken.
We're investigating the cause and will come back here once we have a fix deployed.

**Comment by jstlnd** [comment] 2016-11-09 13:09
@blackarcanis We've now deployed a fix for this issue.
Please get back to us if you have further issues.
Thanks again for you report!

**Closed by jstlnd** 2016-11-09 13:09 UTC
Labels: bug
