### ISSUE TITLE
If Player Requests (play/seek) gets called to fast, Spotify App won't work as intended

### ISSUE THREAD

**Issue by natael** [spotify/web-api#509] opened 2017-04-28 14:17 UTC
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/player/play`
* `GET /v1/me/player/seek`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open Spotify on MacBook (1.0.53.758.gde3fc4b2) and on iMac (1.0.53.758.gde3fc4b2)
2. Trigger play via Player-API
`curl -X PUT "https://api.spotify.com/v1/me/player/play" -H "Accept: application/json" -H "Authorization: Bearer access_token" --data "{\"uris\":[\"spotify:track:2rndJFlCviXXiJNzvO611d\",\"spotify:track:1f133Oqpwft2mGNp5cWqaS\"]}"`
3. Trigger seek via Player-API
`curl -X PUT "https://api.spotify.com/v1/me/player/seek?position_ms=10000" -H "Accept: application/json" -H "Authorization: Bearer access_token"`

#### Expected behaviour:
On both Clients the "Timebar" should be on x:xx and the Track should be jumping to x:xx and be playing on iMac (Spotify Connect Device in this case)

#### Actual behaviour:
Client on MacBook does not show the actual state (after seeking) and just "counts" up from 0:00.
Client on iMac jumps to correct time and plays Track, but Timebar is stuck and other things are happening on the iMac Client:

* Timebar and Play-Button are now dead for me
* Timebar State is stuck
* Play-Button state is stuck (does not change)
* Play-Button does not work (clicking does nothing)
* Spacebar does nothing (not pausing or playing)
* Triggering pause via menu (which is labeled with spacebar) does work
* Timebar seeking restarts track from 0:00
* Restarting the Client does not solve anything
* Reinstallation does not solve anything
* Spotify "About us" does not work anymore (downloaded new Client)
* Spotify "Preferences" does not work anymore
(some things only happened after a Spotify restart)

I did call these Commands after each other, not checking for response state - just the curl requests in this case.

It looks like that the Play- and Seek-Event are messing with each other and a file gets corrupted internally and will result in a Error in the Spotify App.

Tried this again after reinstalling and clearing the Spotify Application Support Folder.
Same thing happened again.

#### Solved it:
* Deleted "Application Support > Spotify" Folder.
* Restart Spotify
* Login
* Works as intended

#### Use Case:
I know that it may be stupid to call the Commands so fast after each other, but for my Use Case, I need a way to start a Track at a given Time.

But maybe it could happen anyway and "destroy" some Spotify Clients :)

**Comment by asmitter** [comment] 2017-05-19 07:12
Duplicate of #524 
Updates will be posted there.

**Closed** 2017-05-19 07:12 UTC
