### ISSUE TITLE
Get Playlist endpoint not applying limit parameter to number of returned tracks

### ISSUE THREAD

**Issue by mherger** [spotify/web-api#115] opened 2015-09-28 22:16 UTC
Other than most other queries the playlists/{id}/tracks query seems to always return 100 items, even if I set limit to 50. Using this query:

https://api.spotify.com/v1/users/yyy/playlists/xxx/tracks?offset=0&limit=50&market=from_token

Expected behavior: return the first 50 tracks of that playlist, with a "next" element pointing to the next 50 items.

Actual behavior: I always get 100 items back. And the "next" item would still use an offset of 50, causing duplicates to be shown in the resulting lists.

First of all the documentation should be clear about the fact that this query doesn't accept a limit parameter and is hard-coded to always return 100 tracks (maximum).

Secondly the "next" value in the returned data should be in line with the hard-coded limit=100 and not return an offset in increments of 50, as following this link would result in duplicate results.

And if I had one more wish, then I would expect this call to behave like (almost?) all other queries, which accept a limit parameter, with the same maximum value (50 or whatever you define as the default maximum value).

**Comment by thelinmichael** [comment] 2015-10-01 14:42
Thanks for creating this issue @mherger! I can't reproduce this issue unfortunately, and I'd be very grateful if you could link to a request using the API Console. For example, I'm trying out [this request](https://developer.spotify.com/web-api/console/get-playlist-tracks/?playlist_id=0AfRSA6JdiTQvQu0zAJNrn&user_id=thelinmichael&limit=5&market=from_token&offset=0) (You need to refresh the access token.), and it does return 5 tracks.

**Comment by mherger** [comment] 2015-10-02 05:23
Hey Michael - good to see you again ;-). Ok, I was partly wrong: I wasn't using the playlists/tracks query, but the playlist (without the tracks):

https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=13thjkLTYZmZvjdz4u6kxh&user_id=nikewomen

This would return a tracks item which would _always_ return 100 items, yet its next element would come with an offset of 50 and a limit of 50. That's wrong.

But getting a playlist's tracks with the /tracks query does indeed work as expected.

**Comment by mherger** [comment] 2015-10-02 05:26
Hold on... did you change this behaviour this very minute?!? Following the link I just posted now returns the correct and expected result...

**Comment by thelinmichael** [comment] 2015-10-05 09:21
I consistently get a response containing 

```json
"next" : "{...}/tracks?offset=100&limit=100"
```

So I'm unfortunately (or fortunately, depending how you look at it.) unable to reproduce that.

The issue I can see however is that the `/playlist/{id}` endpoint accepts `limit` parameter, and will use the argument value in the `next` and `previous` hrefs, but will always return 100 tracks. So you've uncovered a bug!

**Comment by mherger** [comment] 2015-10-06 07:02
Thanks, yes, that's what I'm seeing, too.

**Comment by arirawr** [comment] 2018-01-22 12:15
Hello from the future! At some point, this issue was fixed and I am no longer seeing the described behaviour. Closing the issue 🙂

**Closed by arirawr** 2018-01-22 12:15 UTC
Labels: bug
