### ISSUE TITLE
Feature Request: Check if current user is verified with artist name.

### ISSUE THREAD

**Issue by enkota** [spotify/web-api#766] opened 2018-01-19 23:23 UTC
Hi,

I was wondering if it was currently possible to check if the current logged in user was verified with any of the artists they have added via artists.spotify.com?

Use case for this is when a user logs in, they can choose from one of their artist accounts to verify they are the real artist.

**Comment by arirawr** [comment] 2018-01-22 09:07
Hi @enkota - thanks for the feature request! Looks like this is a duplicate of #10 - you can follow that issue for updates :)

**Closed by arirawr** 2018-01-22 09:07 UTC
