### ISSUE TITLE
Playlist add - allow duplicates flag

### ISSUE THREAD

**Issue by nick-michael** [spotify/web-api#793] opened 2018-02-16 22:17 UTC
#### Endpoint(s):
* `POST /v1/users/{user_id}/playlists/{playlist_id}/tracks`

Enhancement Request:

In a kind of similar vein to #118 and #444 

It would be great to have a request parameter along the lines of `allow_duplicates` which can be used to prevent adding the song if it already exists. It should be more simple than a fully fledged new endpoint

My use case is that I want to allow more than one person to add songs to a playlist, but I also don't want duplicates on the playlist and I can't necessarily keep both devices in sync at all times. I can always make a request to get the playlist before I add the song but that seems a bit more hacky than I would like. Thoughts?

**Comment by arirawr** [comment] 2018-02-20 12:43
Thanks for the request and your use case @nick-michael! I'm going to close this as a duplicate of #118, so you can follow that issue for updates. You can also add your use case to the comments there 😃

**Closed by arirawr** 2018-02-20 12:43 UTC
