### ISSUE TITLE
Project Rosetta support

### ISSUE THREAD

**Issue by BrandonSlaght** [spotify/web-api#232] opened 2016-05-14 11:56 UTC
With the depreciation of the EchoNest API, an app I am currently developing is very crippled because it depended on the Rosetta API to transfer artists between ID spaces. 
 Now I know, Spotify is incentivized to keep all music related traffic on their platform and Rosetta would do the opposite, but an endpoint for this, either on the Web API or elsewhere, would be much appreciated!

**Comment by pedro-otero** [comment] 2016-05-16 16:15
I'm on the same spot as you. There's [another question about it on SO](https://stackoverflow.com/questions/36657505/echonest-api-migration-questions). And if it's not you the one who asked, then there's 3 of us that I know of asking this. I've also thought of the unlikelyness that they migrate this for the same reason you express. However, I would understand if they just didn't mgirate the IDs of other streaming services such as Deezer. But I would like to see migrated the IDs of APIs who just expose data about music. I think it's totally harmless to Spotify and that it actually makes it better over other streaming services having such an API full of possibilities because of this capability to branch out to other APIs and build interesting and engaging apps.

**Comment by BrandonSlaght** [comment] 2016-05-16 16:49
Unfortunately, that was my question :frowning: They never did get back to my email.  I also posted on the MusicBrainz forum (that was the main ID space I was using) but no one could offer any options. Anyways since we're both in the same boat, lets keep each other posted as I really don't want to scrap so much work due to corporate churn.  
Personally I was using Echonest to gather social networks and profile links for artists, but the most important ID translation was a SeatGeek ID for concert ticketing, which I now have no alternative to.  I have nothing against using the Spotify API if it carried over this functionality.

**Comment by mdoyle13** [comment] 2016-06-06 21:46
A product I'm working on made have use of getting spotify ids mapped from facebook ids and other social networks. I really could use this feature back in some fashion.

**Comment by hughrawlinson** [comment] 2017-03-19 22:46
I'm going to close this issue as a duplicate of #241. I'm keeping that one open because it has more reaction emoji, but feel free to add your comments there!

**Closed by hughrawlinson** 2017-03-19 22:46 UTC
