### ISSUE TITLE
Display genre for a specific song, album, or artist

### ISSUE THREAD

**Issue by kolbyomalley** [spotify/web-api#1100] opened 2018-12-03 21:03 UTC
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by bih** [comment] 2018-12-27 17:46
Hello,

Unfortunately I'll need some more information on what the use case of having this information is. It seems like you left the default text in the issue. It seems like a duplicate of #157 #263 so I'll go ahead and close it, and I recommend following the thread to keep up to date with the suggestion.

**Closed by bih** 2018-12-27 17:46 UTC
