### ISSUE TITLE
Playlist owner is missing from response when creating a playlist

### ISSUE THREAD

**Issue by suzannehamilton** [spotify/web-api#632] opened 2017-08-02 19:10 UTC
Issue found on August 2nd 2017.

I believe this issue was introduced at some point since July 1st 2017. That was the last time I ran some code which depended on the playlist creation endpoint, and I didn't see any problems then.

#### Endpoint(s):
* `POST https://api.spotify.com/v1/users/{user_id}/playlists`

#### Scope(s):
* `playlist-modify-private`
* `playlist-modify-public`

#### Steps to reproduce:
1. Open the API Console
2. Call the [create a playlist](https://developer.spotify.com/web-api/console/post-playlists/) endpoint with a user ID, a valid OAuth token for that user and the default POST body:

```
{
  "description": "New playlist description",
  "public": false,
  "name": "New Playlist"
}
```

#### Expected behaviour:
- A new playlist is created in the user's account.
- The response to the POST request contains an `owner` field containing details of the playlist's owner, as described in https://developer.spotify.com/web-api/create-playlist/:

```
{
   ...
   "owner": {
     "external_urls": {
       "spotify": "http://open.spotify.com/user/thelinmichael"
     },
     "href": "https://api.spotify.com/v1/users/thelinmichael",
     "id": "thelinmichael",
     "type": "user",
     "uri": "spotify:user:thelinmichael"
   },
   ...
}
```

#### Actual behaviour:
The playlist is created correctly but the `owner` field in the response is null:

```
{
  ...
  "owner" : null,
  ...
}
```

I've tried creating public and private playlists, and the `owner` is null in both cases.

**Comment by hughrawlinson** [comment] 2017-08-12 17:08
Thanks for the report @suzannehamilton - we'll have a look at this issue and try to resolve it.

**Comment by luis6674** [comment] 2017-09-13 09:55
Is there any update about this bug? It seems to be breaking the communication between our app and Spotify when trying to add a user to follow a playlist. If I can get more technical details I'll comment further.

**Comment by hughrawlinson** [comment] 2018-06-28 12:16
Hi! We pushed a fix for this issue. Please let me know if you're still able to reproduce it, and I'll reopen the ticket. Thanks for reporting!

**Closed by hughrawlinson** 2018-06-28 12:16 UTC
Labels: bug
