### ISSUE TITLE
https://api.spotify.com/v1/me returns display_name null

### ISSUE THREAD

**Issue by kvanzuijlen** [spotify/web-api#435] opened 2017-03-03 09:34 UTC
Issue found on January 20th 2017.

#### Endpoint(s):
* `GET /v1/me`

#### Scope(s):
* all scopes; (including, but not limited to: 
-         'user-read-private'
-         'user-read-birthdate'
-         'user-read-email'
-         'user-top-read'
-         'user-read-recently-played'
)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-current-users-profile` endpoint

#### Expected behaviour:
I have filled in all relevant profile data on `https://www.spotify.com`. I have my profile linked with my facebook account.

I was expecting a public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-private`, including a display_name.

#### Actual behaviour:
(example data)
```
{
  "birthdate": "1937-06-01",
  "country": "SE",
  "display_name": null,
  "email": "email@example.com",
  "external_urls": {
    "spotify": "https://open.spotify.com/user/wizzler"
  },
  "followers" : {
    "href" : null,
    "total" : 3829
  },
  "href": "https://api.spotify.com/v1/users/wizzler",
  "id": "wizzler",
  "images": [
    {
      "height": null,
      "url": "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc3/t1.0-1/1970403_10152215092574354_1798272330_n.jpg",
      "width": null
    }
  ],
  "product": "premium",
  "type": "user",
  "uri": "spotify:user:wizzler"
}
```

**Comment by hughrawlinson** [comment] 2017-03-07 23:24
Thanks for the report! The team are looking into it.

**Comment by rsoldner** [comment] 2017-03-10 14:08
Do you know if this will fix the problem discussed here ?
https://community.spotify.com/t5/Desktop-Mac/Collaborative-Playlist-User-column-shows-IDs-instead-of/m-p/1546651

**Comment by kvanzuijlen** [comment] 2017-03-10 14:12
I don't think a bug in the Web API will fix a problem in the desktop application

**Comment by kvanzuijlen** [comment] 2017-03-17 12:33
Just received an email from developer@spotify.com. Apparantly it's a problem with 'some users that have been created through Facebook and a display name hasn't been resolved.' The developers are, as @hughrawlinson already stated, looking in to the issue.

**Comment by hughrawlinson** [comment] 2017-03-20 16:48
I've realised this issue is a duplicate of #371, so I'll close it and write any follow up on that issue. Thanks for the report!

**Closed by hughrawlinson** 2017-03-20 16:48 UTC
Labels: bug

**Comment by kvanzuijlen** [comment] 2017-03-20 16:55
Hi @hughrawlinson,
I don't think this is a duplicate. When I added this issue I read #371 too, but #371 is about the simple user object not containing a display_name property, right?

This specific issue is about the full user object returning a display_name property with a value 'null'.

**Comment by hughrawlinson** [comment] 2017-03-20 17:02
@kvanzuijlen the issue that causes `display_name` to be null affects on both the full user object and the simple user object causes this issue as well as #371. My reading of #371 didn't suggest the key was missing, just the data.

**Comment by kvanzuijlen** [comment] 2017-03-20 17:06
@hughrawlinson Thanks for the explanation and your fast reply. I subscribed myself to #371.
