### ISSUE TITLE
Genre bugs and ideas

### ISSUE THREAD

**Issue by optimus-philbo** [spotify/web-api#426] opened 2017-02-19 14:52 UTC
There are currently some issues with retrieving genres. Ideally I'd like to retrieve a genre for a track, however this does not seem possible. However, the album object DOES contain genres but they are always empty. I've tried several different albums and they never have any genres. This means I have to fall back to the genres for an artist, which isn't too useful for several reasons:

1. An artist could produce an album that is pop and then later produce an album that is hip-hop. It means that a given track's genre is pretty broad and potentially inaccurate.

2. The list of genres for an artist is quite large and often contains rather odd entries. For instance, for Biffy Clyro one of the genres listed is 'pop-punk'. I don't think I can think of any song/album that is pop-punk by them. 

It would help to have a weight with the genres, or order them so that the most 'common' genre for an artist is first. At least this way I could take the highest weighted/most common genre for an artist.

**Comment by hmhrex** [comment] 2017-02-19 20:39
This was working, but for some reason at some point in the past month, genres disappeared from album query results. I opened an issue yesterday about it as well: #425

**Comment by hughrawlinson** [comment] 2017-03-08 00:13
Hey @optimus-philbo and @hmhrex - the request for albums to have genres is a duplicate of #157, so I'll update you on that issue. We don't have weights for artists genres because that information isn't available to us, and genres are so subjective that the value of such a weighting would be limited. Thanks for getting in touch!

**Closed by hughrawlinson** 2017-03-08 00:13 UTC
