### ISSUE TITLE
User's playlists not showing playlists followed by a Spotify user and sometimes not showing the playlist images

### ISSUE THREAD

**Issue by abrasdev** [spotify/web-api#179] opened 2016-03-04 13:33 UTC
I've been experiencing 2 major issues with the Spotify playlist API. **Both started this week.**

**First Problem:**
When retrieving a user's playlist from ".../v1/users/{user_id}/playlists", the API returns the user's own playlist but is not returning the playlists this user follows on Spotify. Just the ones from Spotify itself. In other words, if I follow a playlist from my friend "John" it won't be returned by this API. But, if I follow a playlist from Spotify, then it will.
**This is also happening with the Spotify app.**

**Second Problem:**
For some reason, some playlists are returning without images. Doesn't matter if they are created by the user, or followed by the user.
The weirdest thing is, if I run this API on the API console, the images are returned as usual. But, if I copy the **same cURL Command** and paste it on Terminal, on my Mac, it won't return the images.

I really can't understand why it works running on the API console and why it doesn't work when running from the terminal. Both are calling the same API, with the same parameters and same tokens.

**As I previously stated, both issues started happening this week. They weren't happening before.**

**Comment by thelinmichael** [comment] 2016-03-04 19:44
Thanks for your report @abrasdev! 

I need some more information to be able to recreate your issue however. Could you please state what the `user_id` is, what user the access token is authorized by (or if it's anonymous), and what scopes/permissions the access token has, e.g. `playlist-read-private`.

For the second problem, it'd be very useful if you could supply the exact cURL command as well as a link to the API Console request. (There's a _Link to this Request_ link on the API Console page.)

**Comment by abrasdev** [comment] 2016-03-04 20:36
@thelinmichael 

**First Problem:**

**user_id** = any user will do. Try **rachelnpg** for example.
**user_id authorized** = abrasmateus
**scopes** = user-read-private, playlist-read-private, playlist-modify-public, playlist-modify-private


**Second Problem:**

`curl -X GET "https://api.spotify.com/v1/users/viticci-us/playlists?limit=50" -H "Accept: application/json" -H "Authorization: Bearer BQCj1jIg_ynU3apK_BVdAZ9_WtTV3FR6MFuan7DU6A8L6l9tRidCyDjE67P9LL6A500JA_Shw3HM2YAjOTiVtdceR9EdhEUkXVgrV88tP3QyV7vjvhm2xHBcB_EgnsefcSSLxjsa9K9ne2zf5maszHOqkA0W7XtZfEE"`

https://developer.spotify.com/web-api/console/get-playlists?user_id=viticci-us&limit=50

Just tried this exact same cURL command on my mac, and it returned without any image. If you want, I can even attach a picture to you. While the console returned all the images.

**Comment by thelinmichael** [comment] 2016-03-05 09:33
@abrasdev, if the access token is authorized by one user (e.g. `abrasmateus`) but the application is making requests for another user's playlists (e.g. `rachelnpg`), private or collaborative playlists won't be returned. Is this aligned with your expectations?

Relevant documentation: [Get a List of a User's Playlists endpoint](https://developer.spotify.com/web-api/get-list-users-playlists/)

I cannot recreate the problem with cover art - both the API Console and the cURL command you've supplied (with a different access token) return images in the `images` array inside the `items` array. Your request asks for 50 playlists - does the response include cover art for any of the playlists, or a single one? Is this issue intermittent?

**Comment by abrasdev** [comment] 2016-03-05 15:49
@thelinmichael 

Yes, that's 100% right and aligned with my expectations. But that is not the problem. The problem is with playlists another user is following.

Take a look at this documentation you linked to. It clearly states in the beginning: _Get a list of the playlists owned **or followed by** a Spotify user._

The "Followed by" part is the problem here. As I said, it started a week ago. And it also happens inside the Spotify app itself. I can't see the playlists my friends are following. You can even try with different users. It's happening to every one I tried.

--

Nope. Not a single one of them returns any image. I'm currently based in Brasil. Maybe there is a problem with the region I'm at? i.e When I run this through the API Console, for some reason it doesn't take in account my IP or something. But when I run in through the cURL command it does?

I can't really tell if its intermittent or not, but as I said, both issues started a week ago and haven't returned to normal since then.

**Comment by thelinmichael** [comment] 2016-03-06 09:09
@abrasdev, I've tried to retrieve playlists using the API for several users and can find playlists that are followed by that user, so I'm not able to recreate the issue. I can't recreate it using the desktop application either, although we are running a lot of A/B tests which may cause your user experience to be different from mine. For example, if you'd go to my user `spotify:user:thelinmichael`, you should see a playlist owned by Spotify Deutchland called Electroküche. You'd also find it if you used the API console. When retrieving playlists for the user you suggested, `spotify:user:rachelnpg`, [using the Console](https://developer.spotify.com/web-api/console/get-playlists/?user_id=rachelnpg), I can retrieve two playlists which are both owned by the Spotify user. Are you not getting the same response?

It's possible that the missing playlist cover art is related to the fact that you're accessing a different data center than the API console, and I'll have to investigate that further. You could check if it's intermittent by making five consecutive requests, if you don't get cover art in any of the cURL requests the issue isn't intermittent. 

Thanks a lot for helping us making the service better, much appreciated!

**Comment by abrasdev** [comment] 2016-03-06 15:53
@thelinmichael Yes. I'm getting the same response. And that's what is wrong and started happening just a week ago. Look at what I said in the first comment:
`the API returns the user's own playlist but is not returning the playlists this user follows on Spotify. Just the ones from Spotify itself. In other words, if I follow a playlist from my friend "John" it won't be returned by this API. But, if I follow a playlist from Spotify, then it will.`
You saw two playlists from `spotify:user:rachelnpg`, both owned by the Spotify user. But she follows ~10 other playlists from other users. Those I can't see. Again, **I could, a week ago.**

----

It's not intermittent. Happens all the time. Started a week ago.

I'm glad to help. Just hope both issues can be fixed.

**Comment by thelinmichael** [comment] 2016-03-06 18:55
@abrasdev, I've looked up this user and two playlists are followed publicly, which are the ones you actually see - i.e. Peaceful piano and Hora de Dormir. The rest are followed privately. (Including some playlists created by Spotify.) So as far as I can tell, this is working according to specification.

**Comment by abrasdev** [comment] 2016-03-06 19:56
@thelinmichael What do you mean by followed privately? How can I follow publicly then? And why was I able to see all of the playlists until a week ago?

Also, what about the playlist images? To me that's the biggest issue. Did you take a look at that?

**Comment by thelinmichael** [comment] 2016-03-06 20:34
@abrasdev, playlists can be followed publicly and privately. If the playlist is followed privately, it's not shown in the user's profile in the Spotify desktop application. The Web API will only return publicly followed playlists unless the request is made on behalf of the user owning the playlists and the user has given the requesting application permission to read public playlists by permitting the `playlist-read-private` scope. A playlist is by default followed privately in the desktop application. An application that [follows a playlist on behalf of a user](https://developer.spotify.com/web-api/follow-playlist/) can decide if the playlist should be followed privately or publicly. 

There hasn't been any changes to how this works in the Web API, and it's very difficult to understand how your application could've retrieved the mentioned user's privately followed playlists without the access token that was used. My suspicion is that the access token was either not authorized by `spotify:user:rachelnpg` but by a different user, or not having the `playlist-read-private` scope. 

Regarding the playlist cover art - it's Sunday. I haven't checked it yet, and I appreciate your patience. ;-)

**Comment by abrasdev** [comment] 2016-03-07 04:00
@thelinmichael hmm, didn't know that. Is this new? One thing that I noticed is that this feature, to follow privately/publicly is only available on the desktop app. The mobile app doesn't give you this option. Am I right? Or there is a way to change this on mobile?

**What I can tell you was working a week ago**: I had an access token authorized by `spotify:user:abrasmateus` and was able to retrieve all the playlists followed privately from `spotify:user:rachelnpg` and any other user. The scopes this access token had were the exact same it has now: `user-read-private, playlist-read-private, playlist-modify-public, playlist-modify-private`. If that was a bug and it is now fixed, I have no idea. But I can tell you that I was able to see it.

-

Sure! Take your time. Let me know when you find out what's going on. Thanks for your help.

**Comment by thelinmichael** [comment] 2016-03-17 10:22
@abrasdev, the concept of private and public playlists is not new. Regarding where to modify the privacy settings of playlists in mobile applications I'm not sure, but you can definitely do so in the desktop application. 

Nothing has been deployed that affects this logic in the Web API, so it does sound to me like the Web API is operating like intended, and the only reason I can see that your application could access `spotify:user:rachelnpg`'s playlists was that they weren't private or that the access token was actually authorized by `spotify:user:rachelnpg`.

We've had some database issues in our data centers in the US, which could have been why you didn't retrieve any cover art. This has however been fixed, so I'm interested in if you're still seeing this problem. If so, could you please provide me with a playlist that does return cover art using the API console? Thanks a lot!

**Comment by abrasdev** [comment] 2016-03-17 13:18
@thelinmichael Yep, I totally understand the concept of private and public playlists. My question was not about the private playlists though, because that's obvious on why I'm not getting them.

The problem was about getting the playlists a user follows. But as I said, I was not aware of a user being able to follow privately/publicly any playlist. I even talked to a couple of other Spotify users and none of them knew this as well. It's a pretty hidden feature. And it is also not available on mobile, which is probably the most used platform. This definitely needs some attention because it is pretty important, specially for those that use the social network inside Spotify.

-

It's been fixed. I haven't experienced this bug since I posted the last update here (10 days ago). Thanks!

**Comment by thelinmichael** [comment] 2016-03-17 13:51
This feels like a good place to close the issue ticket. I agree that it's in Spotify's interest to make sure that users are aware of this feature but given that that's separate from the Web API this is not the right place to continue the discussion. Great that the playlist cover art issue is resolved.

Thanks for the feedback!

**Closed by thelinmichael** 2016-03-17 13:51 UTC
Labels: bug, help wanted
