### ISSUE TITLE
The endpoint v1/me/player/play fails in playlists

### ISSUE THREAD

**Issue by davidhernandeze** [spotify/web-api#974] opened 2018-08-04 23:43 UTC
#### Endpoint(s):
* `PUT https://api.spotify.com/v1/me/player/play`
* `POST https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks`

#### Steps to reproduce:
- Create a new playlist with one song inside.
- Init playlist reproduction using the endpoint `/player/play`
- Add new song to playlist using the endpoint `/users/{user_id}/playlists/{playlist_id}/tracks` (or even in the desktop application)
- Skip the first song.

#### Expected behaviour:
I expected to skip to the second added song.

#### Actual behaviour:
The playback exit to the playlist and plays spotify radio.

**Comment by arirawr** [comment] 2018-08-06 09:42
Hey @davidhernandeze, thanks for the report! This looks like a duplicate of #574. As mentioned over there, this is not something that it's possible to fix. Please follow issue #462 for updates about this kind of functionality.

**Closed by arirawr** 2018-08-06 09:42 UTC
