### ISSUE TITLE
Add support for gapless playback

### ISSUE THREAD

**Issue by paulgoetze** [spotify/web-api#791] opened 2018-02-15 12:29 UTC
Is it possible to start a gapless playback?

Issue found on February 15th 2018.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* user-read-birthdate
* user-read-private
* user-read-email
* streaming
* user-modify-playback-state
* user-read-playback-state
* user-read-currently-playing

#### Steps to reproduce:
1. Send an authenticated `PUT /v1/me/player/play` request with multiple entries in the `uris` data.
  E.g. track ids of [album 6NIsdk340fSXNfSaWyT9EB](https://open.spotify.com/album/6NIsdk340fSXNfSaWyT9EB)

#### Expected behaviour:
Being able to listen to the tracks gaplessly.

#### Actual behaviour:
When listening to the whole passed track list without taking any further interaction, then small gaps appear when switching to the next track. (I use the web playback  SDK, but this should not make a difference for just playing the tracks).

**Comment by bih** [comment] 2018-02-15 13:39
Hey @paulgoetze,

Unfortunately, we don't support gapless playback right now. I'll consider the ability to send multiple tracks as a duplicate of #462 but the gapless playback feature is unique, so I'll leave this open as a feature request 👍

**Comment by paulgoetze** [comment] 2018-02-15 13:46
Great, thanks @bih for the fast reply.

**Comment by bih** [comment] 2018-09-04 12:16
Hello @paulgoetze,

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, we discussed this and decided the engineering work needed to implement this feature isn't possible right now. Today, gapless playback is currently done on the clients locally and not through a centralized infrastructure. For that reason I'm going to close this as <kbd>wontfix</kbd>.

Though I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍

**Closed by bih** 2018-09-04 12:16 UTC
Labels: suggestion

**Comment by paulgoetze** [comment] 2018-09-04 13:10
Thanks @bih for your feedback. 

Just as a follow up: some real world use case to underline the importance of gapless playback:
At [grammofy.com](https://grammofy.com) we use the Spotify Web API & the Web Playback SDK in order to present classical music. As an example, one piece that is really annoying without gapless playback is "The young person’s guide to the Orchestra" by Britten (https://open.spotify.com/album/5toFiJ4D8AozTtHbA53zfE), where the tracks do not match any natural breaks in the piece. People hardly ever listen to this piece/album because of this.

So, as you say this is usually solved client-side: Would that be a valid feature request for the Web Playback SDK then?

**Comment by bih** [comment] 2018-09-04 17:19
@paulgoetze It would be more relevant for the Web Playback SDK. I think it has already been mentioned as crossfading in https://github.com/spotify/web-playback-sdk/issues/27 as there is a lot of overlap between the two. Hope this helps!
