### ISSUE TITLE
No response for user's top artists

### ISSUE THREAD

**Issue by MBFingerhut** [spotify/web-api#642] opened 2017-08-16 14:53 UTC
No response for user's top artists

Issue found on August 15, 2017.

#### Endpoint(s):
* `GET /v1/me/top/{type}` where type is artists

#### Scope(s):
* All

#### Steps to reproduce:
1. Using Tasker and AutoWeb setup with links to API
2. Call equivalent of `Get a user's top artists`

#### Expected behaviour:
The arrays if various artist info should be available for the top 10 artists for that user.

#### Actual behaviour:
Tasker doors out this error consistently

09.51.21/ActionArgBundle key: JoinOutputArray: replace <null> String value with null
09.51.21/E FIRE PLUGIN: AutoWeb Web Service / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 14 bundle keys
09.51.21/E AutoWeb Web Service: plugin comp: com.joaomgcd.autoweb/com.joaomgcd.autoweb.broadcastreceiver.BroadcastReceiverFire
09.51.21/E add wait type Plugin2 time 120
09.51.21/E add wait type Plugin2 done
09.51.21/E add wait task
09.51.26/E Error: 2032794629
09.51.26/E {  "error" : {    "status" : 400,    "message" : "invalid request"  }}

Is the feature still working (looks like it was turned on March if last year)¿
Is there some minimum amount of views to Spotify before the top artists are populated?
Other queries through the Tasker and AutoWeb usage - like looking for specific artists albums - work fine.

**Comment by arirawr** [comment] 2017-08-25 11:24
Hi @MBFingerhut - it looks like you're getting an error for invalid request. Please double check that your query is formed correctly.

You can find the documentation for the endpoint here and try out the request in our interactive console here: https://developer.spotify.com/web-api/console/get-current-user-top-artists-and-tracks

**Comment by arirawr** [comment] 2018-01-22 11:01
Closing this issue as we haven't been able to reproduce the behaviour. Feel free to reopen with reproduction steps if you are still seeing the issue!

**Closed by arirawr** 2018-01-22 11:01 UTC
