### ISSUE TITLE
Cannot retrieve artist's origin

### ISSUE THREAD

**Issue by mmondelli** [spotify/web-api#618] opened 2017-07-20 02:26 UTC
Issue found on July 19th 2017.

#### Endpoint(s):
* `GET /v1/artists/{id}`

#### Scope(s):
* ` -`

#### Steps to reproduce:
I'm working on a project where I need to retrieve the origin or location of the artist. However, the Spotify API does not provide this info as the Echo Nest API used to do.

#### Expected behaviour:
Be able to get the artist's origin (country), based on the Echo Nest API (https://developer.spotify.com/spotify-echo-nest-api/#getting-data-about-artists)

**Comment by bih** [comment] 2017-08-01 09:51
Hey @mmondelli,

Thank you for reaching out regarding the Spotify API. It looks like we [deprecated The Echo Nest](https://developer.spotify.com/news-stories/2016/03/29/api-improvements-update/) just over a year ago and migrated much of that information. One of the few things we didn't was the artist location, but we'll put it back in consideration in the future as a feature request.

Let us know if we can help you in any other way in the meantime. Cheers! 👍

**Comment by leebrother** [comment] 2017-08-05 21:51
I am currently working on a Spotify app called "Now Here This", which will need the artist's origin or location. It will reverse look up the city and the artists coming from there, so if you can put this feature back in the Spotify API, that would be great. We will request this feature - can you let us know when it is available and how soon?

**Comment by jaesley** [comment] 2017-08-09 02:18
I'd love this feature back as well, as I'm working on a small project to find more local music and found Echo Nest to be the most useful and complete version of this information.

**Comment by dannymy** [comment] 2017-10-23 07:29
#210

**Comment by beekgeek** [comment] 2017-11-20 21:41
I'm new to the Spotify API since the Echo Nest API was deprecated, but definitely see value in the artist origin/location data. Hope that this is still on the roadmap for the not too distant future. Trying to avoid cross-referencing with other APIs or building/maintaining a separate database. Thanks for considering!

**Comment by forty9er** [comment] 2017-12-14 14:43
I miss the Echo Nest artist location data too.

**Comment by robostheimer** [comment] 2018-01-04 06:38
I agree.  I had a sweet app called musicwhereyouare which would use your geolocation to create a playlist.  Echonest's artilst_location was perfect for this.  Would love to see that data surfaced in Spotify's api!

**Comment by arirawr** [comment] 2018-01-04 09:28
Hi all - looks like this issue is a duplicate of #210. You can follow that issue for updates.

**Closed by arirawr** 2018-01-04 09:28 UTC
Labels: feature request
