### ISSUE TITLE
Portuguese locale "pt_PT" is not supported (but "pt" is)

### ISSUE THREAD

**Issue by Foldalake** [spotify/web-api#222] opened 2016-04-20 15:08 UTC
I noticed that using "pt_BR" and even just "pt" as locale parameters return results in Portuguese, but "pt_PT" does not.

Not sure whether to release our app using "pt" for European Portuguese, which is not in officially supported locale format ("en_US"), or using "pt_PT" which is currently unsupported..?

Issue found on March 25th 2016.

Steps to reproduce:
[Use the Spotify API console to get Browse Categories](https://developer.spotify.com/web-api/console/get-browse-categories/) and use "pt_PT" as locale parameter.

Expected behaviour: Results are in Portuguese for locale=pt_PT.

Actual behaviour: The results are in English.

**Comment by thelinmichael** [comment] 2016-07-03 08:30
@Foldalake, thanks for reporting this and sticking with the recommended issue format. It's been a while so apologies for the slow response. I've confirmed that `pt_PT` (European Portuguese) isn't supported, but that `pt_BR` (Brazilian Portuguese) is, and will check if that's intended behaviour or if it's a bug.

**Comment by thelinmichael** [comment] 2016-07-05 07:21
@Foldalake, Spotify doesn't actually support Portuguese from Portugal at the moment. Since this issue isn't directly related to the Web API I'm going to close it - the Web API should support `pt_PT` as soon as Spotify as a whole does.

**Closed by thelinmichael** 2016-07-05 07:21 UTC
