### ISSUE TITLE
Reorder on current playing playlist doesn't works

### ISSUE THREAD

**Issue by TLmaK0** [spotify/web-api#1067] opened 2018-10-23 11:59 UTC
Issue found on February 23-10-2018 (but I suspect that it happens since years ago).

#### Endpoint(s):
* `GET  /v1/playlists/{playlist_id/tracks}`

#### Scope(s):
playlist-modify-public
playlist-modify-private 

#### Steps to reproduce:
Open spotify player
1. Create a new own playlist with 20 songs
2. Get spotify playlist uri
3. Open https://developer.spotify.com/console/get-users-available-devices/
4. Click try it
5. Get available device
6. Open https://developer.spotify.com/console/put-play/
7. Set device Id
8. Set playlist uri:
```
{
  "context_uri": {playlist_uri}
}
```
9. Click try it (important step)
10. Open https://developer.spotify.com/console/put-playlist-tracks/
11. Set this request body:
```
{
  "range_start": 10,
  "range_length": 1,
  "insert_before": 1
}
```
12. Click try it
13. Click next buton in spotify player

#### Expected behavior:
Player should play song at position 2

#### Actual behavior:
Player plays song at position 3

Note: If start to play manually it works as expected, but if you use the process described here you found this behavior

**Comment by bih** [comment] 2019-01-03 12:45
Hello @TLmaK0,

Thanks for reaching out! I can reproduce the steps you said above. Reordering a playlists tracks doesn't affect playback when it could be. But this is actually expected behaviour - the playback queue isn't in sync with playlist track order changes.

Given that you're trying to find an engineering workaround for a Play Queue API, I will mark this as duplicate of #462. Let me know if I've misunderstood and I can take another look, and it'd be helpful to mention what use cases you'd have for this.

Cheers!

**Closed by bih** 2019-01-03 12:45 UTC
