### ISSUE TITLE
how can i get the plays number of a song?

### ISSUE THREAD

**Issue by darrenfantasy** [spotify/web-api#539] opened 2017-05-20 03:00 UTC
I have a request to get the plays number for every song.I saw the mac app have the plays number,but I can't get it from the API.
![](http://oic2oders.bkt.clouddn.com/WechatIMG1.jpeg)

**Comment by hughrawlinson** [comment] 2017-05-21 22:31
Hey @darrenfantasy - this is a duplicate of #70. I'll close this issue and if we have any updates we'll post them on that ticket.

**Closed by hughrawlinson** 2017-05-21 22:31 UTC
