### ISSUE TITLE
Track end event

### ISSUE THREAD

**Issue by JanneHarju** [spotify/web-api#610] opened 2017-07-11 15:00 UTC
I'd like to have player API have some kind mechanism for telling me when track is ended without polling /me/player/currently-playing. My app control which track will be played next so I need info when track is ended to know to choose next one. It could be callback like this:

this.http.post(
         '/me/player/**eventsubscribe**',
         '{event-type: 'track-end', callback: 'http.//someaddress.com/trackendcallback' }',
         {headers: headers})

Parameters are **event-type** which tells API which event we are subscribed and **callback** which is callback address same way as we give callback address in token flow. So spotify calls my callback address when specific event occure, in my case it will be when track ended. 

I added question also to stackoverflow whether there is already somekind solution to this problem. https://stackoverflow.com/questions/45028762/is-there-a-way-to-detect-when-spotify-track-is-ended-using-web-api

**Comment by seahorsepip** [comment] 2017-07-16 23:06
This has been requested multiple times before and can be considered a duplicate of #492 I think.

**Comment by JanneHarju** [comment] 2017-07-29 07:22
Yeah its simillar if that
https://github.com/spotify/web-api/issues/492 will return information when track is ended status also and not only playback.

**Comment by hughrawlinson** [comment] 2017-08-13 11:20
I'll close this as a duplicate of #492, but that issue looks pretty bare, so please feel free to add your use case to that issue.

**Closed by hughrawlinson** 2017-08-13 11:20 UTC
