### ISSUE TITLE
All my playlists were removed!

### ISSUE THREAD

**Issue by dsiskov** [spotify/web-api#992] opened 2018-08-19 16:30 UTC
I already wrote on spotify support. (https://community.spotify.com/t5/Accounts/All-playlists-are-removed-only-folder-structure-is-still-there/td-p/4549639)
My use-case:

- was using **[spotify-web-api-node](https://github.com/thelinmichael/spotify-web-api-node)** on a testing environment (node.js and react, trying it out)
- authenticated with 
`var scopes = ['user-read-private', 'user-read-email', 'playlist-modify-private', 'playlist-read-private', 'playlist-read-collaborative', 'playlist-modify-public', 'user-library-read'],
	clientId = "acd37a21c8664aa69e18fd1afdb2872c"...`

- invoked `spotifyWebApi.getUserPlaylists('dsiskov', { "limit": 50 })` which worked fine on Friday
(spotify-web-api-node is using your routes for retrieving playlists)
result:
today all my playlists are gone!

example: spotify says [My Shazam Tracks](https://open.spotify.com/user/dsiskov/playlist/4YH3V9NtgCNypGtKewUjGG) is mine, but not displayed in my library

I really can't see how could this happen, need some help ASAP!
Thanks in advance
Dragan

**Comment by dsiskov** [comment] 2018-08-19 16:58
could it be a bug with requesting access to scopes
**user-read-private** and **user-library-read**?

**Comment by BloodShura** [comment] 2018-08-21 19:48
Uhm, I don't think it's even related to the Spotify API? AFAIK there's no endpoint for deleting a playlist or something like that, so, if it was caused by the Spotify API, it would be a **really weird internal bug**.

Nevertheless, you can always recover your playlist on your [Spotify's account settings](https://www.spotify.com/br/account/recover-playlists/).

**Comment by arirawr** [comment] 2018-08-27 08:55
Hi @dsiskov - sorry to hear you're having issues with your playlists! From the forum post you linked, it looks like you were able to get some help from Customer Support, so hopefully you're back to rocking out to all your playlists again already! 🎸 

From the API perspective, I can't think of any way this would be related to the API usage you described. I'll bring the report to the Web API team regardless. When you make an API request to `GET /v1/me/playlists` (either through the code you pasted or through the Web Console [here](https://developer.spotify.com/console/get-current-user-playlists/)), do you still see your playlists? If so, this may be an issue with the Spotify client you're using. Make sure to download the latest updates and restart the client. If the issue is still not resolved, please let me know the client version you're using 🙂

**Comment by dsiskov** [comment] 2018-08-27 09:05
Hi @arirawr 
Thanks for your attention.
I have my playlists restored manually now, however, after this happened I tried the API (me/playlists)
Nothing was there.
I tried opening all clients I could think of (android/ios/windows/web), all latest versions - same result.
Hope this helps to pinpoint the problem!

**Comment by arirawr** [comment] 2018-08-27 09:06
That's very strange! Do you still have the exact code you used? Is it possible that you called another API endpoint than the GET playlists one you mentioned?

**Comment by arirawr** [comment] 2018-08-27 09:26
Alright. As you can see in the source for that library, the [`getUserPlaylists` function](https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L446) only makes GET requests, so it would be impossible for that call to delete your playlists.

As I mentioned, I will still bring this to the team but as it's resolved on your end and not reproducible, I'm going to go ahead and close this issue. If I find anything further, I'll post here.

**Closed by arirawr** 2018-08-27 09:26 UTC
Labels: more info needed, question
