### ISSUE TITLE
When playback on sonos invalid 403 message

### ISSUE THREAD

**Issue by thordavid** [spotify/web-api#740] opened 2017-12-08 20:02 UTC
Issue found on December 8 2017.

#### Endpoint(s):
* Request: POST https://api.spotify.com/v1/me/player/next

#### Steps to reproduce:
1. Use spotofy native app to start music on Sonos speaker
2. Call Request: POST https://api.spotify.com/v1/me/player/next

#### Expected behaviour:
Successful outcome to commmand
Request: POST https://api.spotify.com/v1/me/player/next

#### Actual behaviour:
403 Forbidden.. Spotify connection only works with a premium Spotify account.

**Comment by arirawr** [comment] 2017-12-09 09:08
Hi @thordavid! Thanks for the report. As documented [here](https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/), the Player endpoints only work with Premium accounts. Are you using a Free or Premium account to make the request?

**Comment by thordavid** [comment] 2017-12-09 15:37
I am using a family premium account 

dthor@sent.com is the account

All web api calls work unless playback is on a sonos device and then I get the reporter error

**Comment by arirawr** [comment] 2017-12-10 10:47
Ah, alright. Looks like your device isn't controllable through the Web API. From the [Web API Connect guide](https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/):

> To determine if you should send controlling commands to a certain device, check the is_restricted flag on a device object. If you receive the 403 FORBIDDEN code back, this means that the currently active device (or targeted device) is not controllable through the Web API.

This is expected behaviour, so I'm going to close this issue.

**Closed by arirawr** 2017-12-10 10:47 UTC
