### ISSUE TITLE
Local Google Cast devices on my Wi-Fi are not returned by Web API

### ISSUE THREAD

**Issue by aartek** [spotify/web-api#787] opened 2018-02-09 21:37 UTC
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/player/devices`

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
1. Turn on your chromecast device
2. Open the API Console
3. Call the `get-users-available-devices` endpoint

#### Expected behaviour:
Should return all available user's devices, also the "Google Cast" type that can be i.e Android TV or Chromecast.

#### Actual behaviour:
I can see my available "Google Cast" devices in the iOS Spotify app, but cannot list them through the Web API. Only "Spotify Connect" devices are returned.

iOS app:
![img_659ce9cf6fc7-1](https://user-images.githubusercontent.com/5053151/36050997-e4750688-0de8-11e8-9233-900ae4358904.jpeg)

API Response:
<img width="525" alt="api-screen" src="https://user-images.githubusercontent.com/5053151/36051136-659a4d5e-0de9-11e8-8eeb-27ef4c37bd58.png">

**Comment by bih** [comment] 2018-02-15 14:14
Hey @aartek,

Thanks for the report! I can't seem to reproduce this issue. It's difficult for me to attempt to do so. Have you tried upgrading your Chromecast OS version? It's worth noting some older devices using Spotify (or older versions of Spotify) might not support Connect and therefore might not show up in the API.

I'll leave this open for a short while in case other people are getting this issue. Otherwise I think the error might be unrelated to the Web API and more related to the firmware of your other devices using Spotify.

**Comment by jsimonsson** [comment] 2018-02-15 14:34
Also, it could be that the device is only detected on the network, you are actually not yet logged in on the chromecast as "you". Once you actually select it and login on it it may appear in the Web API.

**Comment by bih** [comment] 2018-02-15 15:01
That's a good point, @jsimonsson. The Connect Web API does not have the context of your Wi-Fi network where your mobile phone does, and so it would not show anything that is specific to your Wi-FI network through the Web API. The solution in this case would be manually login through your TV.

**Comment by aartek** [comment] 2018-02-15 19:37
Ok, thanks for your answers. Now I get it, and it seems that I won't be able to do my scenario with the Web API. The iOS app probably can [discover](https://developers.google.com/cast/docs/ios_sender_integrate) chromecast devices and cast to them and that's why I was able to see the devices only on my phone.  So you can close this issue, because it's not a bug. 

If you're interested, there is my use case:
I have Raspberry Pi with nodejs server, connected with HDMI to my TV. I can turn on my tv by making a request to that server, which turns on the TV by using hdmi-cec client. From that moment I can open Spotify app on my phone and play the music selecting my TV as Google Cast device, because it is visible there.
But I'm lazy and I wanted to be able to achieve that with one click (one http request), without even opening the spotify app on my phone. In this scenario nodejs server should turn on the tv, get my devices by WebAPI, check if the list contains my TV, and then play the predefined playlist. I've implemented that but the problem was that the TV wasn't returned from /devices endpoint, so it didn't work. Thanks to your answers I understand why. 

The workaround will be to call from raspi the same request as that one which turns on the Spotify using Google Cast from iOS app, instead of using WebAPI. 

In the future, you could provide an library which would allow users to play the music on the GoogleCast devices in their network. That would be very useful for the smart home projects! :)

**Comment by MoonshineSG** [comment] 2018-03-08 12:05
> The workaround will be to call from raspi the same request as that one which turns on the Spotify using Google Cast from iOS app, instead of using WebAPI.

Did you manage to make this work? I am doing something very very similar and it’s quite frustrating that the Spotify chromecast can’t be “activated” via the api

**Comment by aartek** [comment] 2018-03-10 15:38
> Did you manage to make this work? I am doing something very very similar and it’s quite frustrating that the Spotify chromecast can’t be “activated” via the api

@MoonshineSG , Yes I did. You can check in my repo: https://github.com/aartek/spotify-chromecast-player

**Comment by MoonshineSG** [comment] 2018-03-12 04:17
@aartek yes, mine is similar, just using python :D https://github.com/MoonshineSG/spotify.google

**Comment by arirawr** [comment] 2018-04-05 08:55
Closing this as we've determined it isn't a bug. The Spotify mobile app can detect Google Cast devices on your WiFi network, but the Web API [does not return these devices](https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#devices-not-appearing-on-device-list).

Looks like a couple of you have found some clever workarounds that should help others with this issue :)

**Closed by arirawr** 2018-04-05 08:55 UTC
Labels: bug

**Comment by timdonovanuk** [comment] 2018-04-24 10:17
Please fix your API spotify. This is stupid. Same comment as before: 

https://github.com/spotify/web-api/issues/834#issuecomment-383880081

**Comment by joshhodgson** [comment] 2018-04-24 11:10
@timdonovanuk Chromecasts aren't Spotify Connect devices until they get woken up, they aren't in constant communication with Spotify like a "real" Connect device would be (eg Amazon Echo). Your phone uses the Chromecast API to detect and then wake up the Chromecasts.. there's no reason you couldn't do the same.

**Comment by timdonovanuk** [comment] 2018-04-24 12:00
@joshhodgson this isn't just Chromecast devices this affects. Sonos devices exhibit the same behaviour. Even if they are playing Spotify, and are listed as Spotify Connect devices in the mobile/desktop app (so you'd agree they are thus Spotify Connect Devices!)...you cannot see them via the api that's supposed to list Spotify Connect devices.

Apparently Spotify clients uses a secret API that we're not allowed to use?

**Comment by aartek** [comment] 2018-04-24 12:33
> Apparently Spotify clients uses a secret API that we're not allowed to use?

@timdonovanuk If you want to cast something to google cast device, you have to find it using google's api. Also, your devices must be in the same network. Discovery is done i.e in this project https://github.com/thibauts/node-castv2-client

You can read more here: https://developers.google.com/cast/docs/discovery 

This article may also be helpful:
https://developers.caffeina.com/reverse-engineering-spotify-and-chromecast-protocols-to-let-my-vocal-assistant-play-music-ada4767efa2

**Comment by MoonshineSG** [comment] 2018-04-24 12:36
Yes, mixing the Spotify with discovery and “fake” Spotify client is a workable hack. (https://github.com/MoonshineSG/spotify.google)

**Comment by joshhodgson** [comment] 2018-04-24 12:54
> Apparently Spotify clients uses a secret API that we're not allowed to use?

Spotify clients use another completely separate API to communicate to devices which can't talk to the Spotify servers.
