### ISSUE TITLE
song added to playlist put in wrong position

### ISSUE THREAD

**Issue by jpiepkow** [spotify/web-api#529] opened 2017-05-12 17:47 UTC
#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists/{playlist_id}/tracks`

#### Steps to reproduce:
I honestly have no idea how to reproduce out of 5 hours of adding songs every 3 minutes to a playlist it happened 4 times where the added song was put as the first song of the playlist.

#### Expected behaviour:
Add a song to playlist with no position in query param and the song is appended to the playlist.

#### Actual behaviour:
On rare occasions when not putting a position in query param the song will still get added to the beginning of the playlist.

Additional note: I have been testing these same endpoints over the past 4 months and only recently(as of this week) have I seen this bug.

**Comment by jpiepkow** [comment] 2017-05-15 14:16
Is there any update on this issue or anything else running into it because in doing some more tests today creating 5 separate playlists and calling add song with now position query param every time it put the song at the beginning of the playlist as compared to the end like stated in the doc's(and how it behaved previously)

**Comment by jpiepkow** [comment] 2017-05-15 14:32
In using the post track test:

https://developer.spotify.com/web-api/console/post-playlist-tracks/#complete

It seems that every time a new track is added it is added to the beginning of the playlist and not the end as how this endpoint worked previously and how it is described in the docs. Any news on this would be super helpful for me and my application.

**Comment by jpiepkow** [comment] 2017-05-16 17:25
When you have any news on this get back to me please. I can't make it through an hour playlist adding a song every 3 minutes without one eventually being added to the beginning not the end of the playlist. I may have to call out to get the playlist length and explicitly state the position to last but I would MUCH rather not make another call when the api stated that this endpoint should append a playlist if no position param is set. Also again this was not an issue for me until around 2 weeks ago.

Thanks!

**Comment by jpiepkow** [comment] 2017-05-17 14:08
Last update: I am not explicitly passing the position (end of playlist) each time I add a track because I was running into issues stated above very frequently over the past week. The issue above still exists but is not so much of an issue for me now. I will keep this issue open as I do believe it is something worth looking into.

**Comment by asmitter** [comment] 2017-05-18 07:12
Hey @jpiepkow - Just wanted to let you know that this is on our list to investigate.
Are there any factors which increase the predictability of the bug? For example, quickly adding tracks, or how recently the playlist was created?

(Has anyone else seen this issue?)

**Comment by raffjones** [comment] 2017-05-18 08:18
I am also seeing this issue using the API. When no `position` option is explicitly passed, the track will sporadically be added in the wrong place - usually at the start of the playlist. Playlists created using the API have ordering all over the place and there is no way to sort them.

**Comment by asmitter** [comment] 2017-05-18 08:48
Thanks for the extra info @raffjones 
What order were the tracks added - as per the screenshot? Or has any manual ordering taken place?

**Comment by raffjones** [comment] 2017-05-18 08:55
@asmitter The timestamps do show when they were added, with no manual ordering on any of those tracks. I'll see if I can set up a test bed in our application to get more debugging info.

**Comment by raffjones** [comment] 2017-05-18 09:09
@asnitter - here's another example that is completely untouched. Start by looking at what open.spotify.com shows. Starts with James Brown - Sex Machine, ends with The Blue Nile - The Downtown Lights.

[open.spotify.com](https://open.spotify.com/user/raffjones/playlist/4C8EgSat03Chs06pj0CwUD)

My API query to get the playlist shows exactly that too.

But then in Spotify, with no edits / re-ordering, or custom view ordering, it starts with The Blue Nile, ends with Bill Withers. There is no rhyme nor reason to it.

[Start](https://www.dropbox.com/s/hke8adomjijuk92/1.%20makeitfunky-start.png?dl=0)
[End](https://www.dropbox.com/s/l01o8a5kxdjx6v2/2.%20makeitfunky-end.png?dl=0)

**Comment by asmitter** [comment] 2017-05-18 09:18
Thanks for the info. To summarise:

Adding tracks to a playlist via Web API, without specifying "position":
 - timestamp for when the track was added is correct
 - The order in which they were added is not reflected when retrieving via web api
 - The order in which they were added is not reflected in the desktop client, and is different from when retrieved via web api.

Does a delay between subsequent track additions make any difference (e.g. waiting 5 second between each track addition)?

**Comment by raffjones** [comment] 2017-05-18 09:23
@asmitter Your summary is correct, except that the order in which they were added IS reflected when retrieving via web api as far as I can see. This is also the order shown on open.spotify.com for any given playlist.

I can also add that when I view the same playlist on the mobile client, the order is as expected - this issue is only affecting the desktop client. Going offline/back online and logging out/back in has no effect.

I can also confirm that a delay between track additions has no effect. The additions to the two playlists I sent you examples of were added one by one over a period of days.

**Comment by asmitter** [comment] 2017-05-18 09:32
OK - so what you see in via the Web API and on the open page is correct. That helps narrow it down, thanks.
I'll take this info to the teams. We'll need to do some digging around, so it might take a little while to come back.

**Comment by jpiepkow** [comment] 2017-05-18 13:38
A quick note at least for the multiple times I got the issue. It always placed the song at the beginning of the playlist and was the same across all devices(did not check the web api return for playlist though) This was adding a song every 3 minutes to a brand new playlist. I can not say if it would be an issue to an older playlist or not.

**Comment by raffjones** [comment] 2017-05-18 13:55
@jpiepkow Did you check at your playlist on open.spotify.com? I found the order there was consistently correct and in line with my API result. It was only the desktop client that was wrong.

**Comment by dbrowndan** [comment] 2017-05-22 16:45
FWIW, this has been happening to me too. I had to build a Chrome extension to auto-refresh the web player at the end of each song to get the right order since the desktop player wasn't behaving. New tracks went to the top in the player, even though the tracklist from the API showed them at the bottom.

**Comment by jetinski** [comment] 2017-06-08 09:29
I have the same issue as described by Laamanni (not having changed my code but the expected behaviour changed). Now songs get added at the beginning of the playlist, the timestamp is empty, ...
Is there any chance on a quick fix on this?

**Comment by dbrowndan** [comment] 2017-06-08 17:40
RE: Quick fix

Would anyone want to see/use my Chrome extension that refreshes the web player when a song is almost done? The refresh (usually) gets the correct playlist order and then the extension automatically clicks play on the correct next track.

I know it depends on what kind of application your making but if anyone could use this, let me know and I'll get it up on GH somewhere.

Hoping it's just a temporary measure.

**Comment by jpiepkow** [comment] 2017-06-08 17:56
Also anyone else running into this issue my fix that worked for me was running the getplaylist endpoint and then using the playlist length -1 as the position of the song I am trying to add. Explicitly stating the position of the song your adding is a temp fix.

**Comment by dbrowndan** [comment] 2017-06-08 18:43
https://github.com/dbrowndan/jj-helper

It's incredibly quick and dirty but it worked 90+% of the time for me. Improvements welcome.

And thanks for that workaround. That might work perfectly for me.

**Comment by jpiepkow** [comment] 2017-06-08 19:08
@dbrowndan Awesome. Just tried it out and it seems to work for my applications. I will most likely base my own custom extension off of it. Thanks the code example is very helpful!

**Comment by asmitter** [comment] 2017-06-09 17:20
Hi all - thanks for the patience while we look into this.
We've pushed a fix that should help remediate the issue. It's a little tricky to validate this end as the issue is so unpredictable, so please have another go and let us know if you still experience tracks being inconsistently added to the start rather of the end of a playlist.

**Comment by dbrowndan** [comment] 2017-06-09 17:32
Thanks for looking into all this! It wasn't fixed for me yet in the desktop player. I tried uninstalling and reinstalling. Will this take time to kick in?

**Comment by asmitter** [comment] 2017-06-09 17:38
@dbrowndan The issue was likely at the time the tracks were added, so playlists created before now won't be fixed by this update. Try creating more playlists via the API as you were and see if things still get added in the wrong order. There's no update to the Desktop player needed.

**Comment by jetinski** [comment] 2017-06-11 17:43
I've just re-created a playlist, but the bug is still present --> playlist is in the wrong order :(
Do I have to update anything on the client-side or is it correct to assume the fix is completely done on the server-side without the need to update any libraries?

**Comment by asmitter** [comment] 2017-06-12 18:20
@jetinski thanks for coming back. We assumed it was server-side but based on your feedback and further investigation it may not be. We'll keep investigating.

**Comment by Laamanni** [comment] 2017-06-13 16:57
It seems that the bug is now fixed, at least for me. I tried adding songs to previously created playlists using Shazam and my own app and both added songs to correct positions and showed correct timestamps.

**Comment by asmitter** [comment] 2017-06-15 09:50
Thanks for the report @Laamanni 
We rolled out an update server-side which we believe addresses the issue. If you can still create new playlists where the ordering is incorrect, please reopen the ticket and post the API calls you are making and the uri of the playlist.

**Closed by asmitter** 2017-06-15 09:50 UTC
Labels: bug
