### ISSUE TITLE
Genres are not returned for artists

### ISSUE THREAD

**Issue by prullenbak** [spotify/web-api#263] opened 2016-07-12 12:42 UTC
Hi,

It seems like the https://api.spotify.com/v1/artists/{id} endpoint (almost) never returns any genres? Maybe I'm doing something wrong, but for example a band like muse (/v1/artists/12Chz98pHFMPJEknJQMWvI) should have some genres?

Thanks!

**Comment by hughrawlinson** [comment] 2016-08-03 12:57
Hey @prullenbak, thanks for getting in touch. This issue is a duplicate of #157, please see that issue for any updates. Thanks!

**Closed by hughrawlinson** 2016-08-03 12:57 UTC

**Comment by buckmaxwell** [comment] 2019-10-25 15:40
This issue is not a duplicate of #157, they are different endpoints right?
