### ISSUE TITLE
Search requests return different results depending on parameter order

### ISSUE THREAD

**Issue by marco-eckstein** [spotify/web-api#943] opened 2018-07-10 18:53 UTC
Issue found on July 10th 2018.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
Issue the following GET requests:

1. https://api.spotify.com/v1/search?q=isrc%3AGBF089190013&market=DE&type=track
2. https://api.spotify.com/v1/search?q=isrc%3AGBF089190013&type=track&market=DE
3. https://api.spotify.com/v1/search?q=isrc%3AGBF089190013&market=DE&limit=20&offset=0&type=track
4. https://api.spotify.com/v1/search?q=isrc%3AGBF089190013&type=track&market=DE&limit=20&offset=0

#### Expected behaviour:
In all responses, "available_markets" is the same. For requests 3 and 4 (which are identical but with a different order of parameters), responses are identical.

#### Actual behaviour:
Request 4 yields different arrays for "available_markets". "CA" and "US" are included, while they are not included for the other requests.

**Comment by marco-eckstein** [comment] 2018-07-11 17:05
After some more experimentation, also with GET /v1/tracks/{id} for the appropriate track, I cannot reliably reproduce the aforementioned behavior anymore. Whether "available_markets" includes "CA" and "US" seems to be random. I suspect the value has recently been edited, and the change has not yet fully propagated through Spotify's network of servers/caches, so you get stale data by chance. Is this assumption correct?

**Comment by bih** [comment] 2018-07-24 14:09
Hi @marco-eckstein,

I was unable to reproduce the issue. It may not have been that changes were being made to Spotify content, and may not be reflective of the Search API itself.

Unfortunately, as this issue is not able to be reproduced, we cannot diagnose it. I will therefore close the issue and mark it as resolved. If you continue to have issues, please feel free to re-open the ticket and reference this issue (#943).

**Closed by bih** 2018-07-24 14:09 UTC
