### ISSUE TITLE
Migration of Echonest's Rosetta Stone functionality

### ISSUE THREAD

**Issue by eugenio11** [spotify/web-api#241] opened 2016-05-30 17:09 UTC
Echonest Rosetta Stone allowed to refer to an artist using IDs coming from different spaces, e.g. getting the Twitter ID of an artist starting from the Spotify or Deezer ID.
I couldn't believe this extremely useful feature was going to die, but apparently there is no mention of that in the Spotify API doumentation and the echonest API will stop working tomorrow.

Is there any plan to support Rosetta Stone?

Thanks.

**Comment by mdoyle13** [comment] 2016-06-06 21:43
I would also really like to know if this feature will come back or is still available somehow

**Comment by thelinmichael** [comment] 2016-07-02 10:27
There are no short-term plans to provide the same functionality in the Spotify Web API. 

#249 handles Twitter usernames in particular.

**Comment by wannabesrevenge** [comment] 2016-12-27 19:52
this is one of the most useful API's that echonest provided. are there plans to implement this even on a long term roadmap? i wouldn't be surprised at all if there were no plans, and none of us that used echonest's api should be surprised that Spotify would want to nerf Echonest's original functionality.

**Comment by BrandonSlaght** [comment] 2017-03-20 00:53
My issue was closed as a dupe of this, but has there been any progress internally? No offense, but shutting down their API after acquiring EchoNest seems like a selfish and anticompetitive decision on Spotify's part.

**Comment by jshakes** [comment] 2017-04-18 12:15
I would also love to see this feature reintroduced to help me map artist accounts in Spotify to their counterparts in Songkick, rather than relying on potentially ambiguous string searching.

**Comment by arirawr** [comment] 2018-09-18 12:41
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

For the use case of finding a track or album on other platforms, we do have [external IDs returned by the API](https://developer.spotify.com/documentation/web-api/reference/object-model/#external-id-object), including ISRC and UPC. You can also search by these IDs in the Search API. We unfortunately do not have similar functionality for artists.

**Closed by arirawr** 2018-09-18 12:41 UTC
Labels: suggestion
