### ISSUE TITLE
Add play to 'time' option in the endpoint /v1/me/player/play

### ISSUE THREAD

**Issue by Bungleoid** [spotify/web-api#648] opened 2017-08-25 16:27 UTC
I would like to be able to make a PUT request to play/resume play up to a specified point within a track.

#### Use Case:
I'm trying to play excerpts of songs in my application.
I currently have to 'seek' then play for a duration which is timed from my application.
I would like to be able to 'seek' then 'play_up_to' with the server stopping the stream accurately every time.

#### Endpoint(s):
/v1/me/player/play

**Comment by hughrawlinson** [comment] 2017-09-06 11:50
Hi @Bungleoid - we'll take this as a feature request :)

**Comment by Bungleoid** [comment] 2017-09-06 11:52
Hi Hugh, 

Nice one, thanks. 
John

**Comment by hughrawlinson** [comment] 2017-10-26 22:58
Hey, I realised this is a duplicate of #596. We'll close this issue and post updates on that one.

**Closed by hughrawlinson** 2017-10-26 22:58 UTC
Labels: feature request

**Comment by Bungleoid** [comment] 2017-10-29 09:04
Hi Hugh, 

Not an exact duplicate, as my request was to play to a particular point in a track as well. #596 merely request to start play at a particular point.

Regards
John
