### ISSUE TITLE
Internal server error searching for playlists with query "rock" and offset=50,limit=50

### ISSUE THREAD

**Issue by jgranstrom** [spotify/web-api#517] opened 2017-05-05 08:43 UTC
Issue found on April 23th 2017 (first seen, and occurred every day since).

#### Endpoint(s):
* `GET /v1/search?q=rock&type=playlist&limit=50&offset=50`

#### Scope(s):
* None

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with `q=rock`, `type=playlist`, `limit=50`, `offset=50`

#### Expected behaviour:
A set of 50 playlists matching the `rock` query

#### Actual behaviour:
500 Server Error (consistently)

#### Additional info:
Works with same query and offset 0: `q=rock`, `limit=50`, `offset=0`
Works with other query and offset 50: `q=edm`, `limit=50`, `offset=50`

**Comment by hughrawlinson** [comment] 2017-05-05 08:47
Thanks for getting in touch @jgranstrom - this looks like a bug to me. I've asked the team to take a look!

**Comment by jgranstrom** [comment] 2017-05-05 09:18
@hughrawlinson thank you!

I tested a few more times and it seems to break when reaching a playlist at position `90`.

It breaks for `offset=45` and `limit=45`, and `offset=50` and `limit=40`, and `offset=40` and `limit=50`, and so on

While it works for `offset=45` and `limit=44`, and `offset=50` and `limit=39`, and `offset=39` and `limit=50`, and so on

**Comment by asmitter** [comment] 2017-05-11 06:38
@jgranstrom we were able to reproduce it, thanks for the extra steps.
You're correct that an item in that position was causing the error. We've narrowed it down to why and will work on a fix.

**Comment by asmitter** [comment] 2017-05-15 10:44
Hi again @jgranstrom 
We just deployed a fix for this issue.
Thanks again for the report. Let us know if you have any more problems.

**Closed by asmitter** 2017-05-15 10:44 UTC
Labels: bug
