### ISSUE TITLE
Playlist tracks.total sometimes differ from actual value

### ISSUE THREAD

**Issue by JeroenKappe** [spotify/web-api#961] opened 2018-07-23 19:26 UTC
Issue found on July 23th 2018

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* none

#### Steps to reproduce:
1. Open the API Console
2. Call the `GET /v1/users/{user_id}/playlists/{playlist_id}` endpoint
3. Sometimes the tracks.total then differs

#### Expected behaviour:
tracks.total giving the same value as that which can be seen in the Spotify deskop application. (When clicked on the specified playlist).

#### Actual behaviour:
tracks.total sometimes can differ from the actual value. When the value is wrong, the value is always bigger then the actual value.

#### What I think the problem is:
As far as I know unplayable tracks seem to be counted as well. And on the Spotify application it is not. Hence with playlists containing unplayable songs, this number will of course differ.

**Comment by arirawr** [comment] 2018-07-24 11:37
Hey @JeroenKappe - this is a duplicate of #958. We're looking into the issue!

**Closed by arirawr** 2018-07-24 11:37 UTC
