### ISSUE TITLE
API search results discrepancy with web player results (same query)

### ISSUE THREAD

**Issue by bcollazo** [spotify/web-api#959] opened 2018-07-21 00:25 UTC
Is there a reason why search results from the web player (https://open.spotify.com) differ from the ones obtained via the API for the same query? I am trying the query 'bad bunny amor'.

In the WebPlayer (https://open.spotify.com/search/results/bad%20bunny%20amor) I get results; but when I do https://api.spotify.com/v1/search?query=bad+bunny+amor&type=track&offset=0&limit=5 via the Search API, I get no results.

Thanks in advanced!

**Comment by jscholes** [comment] 2018-07-21 16:49
You should include a market parameter when searching via the API.  For convenience, you can set it to "from_token", which will instruct the API to use the market in which your account is registered - for this to work you must have authorized your account and obtained the user-read-private scope.  Otherwise you can set it to a two-letter country code.

**Comment by arirawr** [comment] 2018-07-24 12:16
Hey there, this looks like a duplicate of #667. Please follow that issue for updates.

**Closed by arirawr** 2018-07-24 12:16 UTC
Labels: duplicate
