### ISSUE TITLE
Offset limit to 10000 is not enough

### ISSUE THREAD

**Issue by dotfield** [spotify/web-api#862] opened 2018-05-03 20:27 UTC
Your template is useless and means nothing to me.

I run a program that finds new releases. In fact the main reason I use Spotify is because you have had this feature that I can get ALL the new releases and filter what I want from them.

In the past I had no issue with offset over 10000. Today I was getting failures when the search results hit the limit.

I wouldn't need 10000 search results if I could actually limit the return to "albums" with no more than 4 tracks.

Issue found on May 3rd 2018

#### Endpoint(s):
* https://api.spotify.com/v1/search?query=tag%3Anew&offset=10000&limit=50&type=album&market=GB

#### Expected behaviour
More results, until there are none left.

#### Actual behaviour:
404 Not found error.

**Comment by dotfield** [comment] 2018-05-03 21:10
I tried this but it was even worse:

https://api.spotify.com/v1/browse/new-releases?country=GB&limit="
						 << limit << "&offset=" << offset;

Only 500 results. 500??? 

I want ALL the new releases, not just the ones Spotify wants me to see.
How does Spotify know what I'm interested in?
Return me the lot and let me decide.

**Comment by dotfield** [comment] 2018-05-03 22:16
In the search api documentation it mentions query filters but doesn't give a proper list of what query filters are available. It gives an example, not a comprehensive list of available ones. For example it mentions year but that isn't mentioned previously as an available query filter.

If there is a query filter that allows me to limit the release date to just 1 week instead of two, I run this weekly so that would suffice. Perhaps let me specify the number of days etc.

In addition, I mentioned the number of tracks: let me select 1-4 tracks only. I want singles and EPs not albums. album_type=single doesn't work. And it wouldn't be accurate anyway as many singles are tagged as albums.

Meanwhile, 10000 is far too low a limit. My result is about a fifth of the size it was last week.

**Comment by Dyphen** [comment] 2018-05-04 23:39
This started happening to me this week as well. For years the offset went to 50k, now errors out after 10k. Is there any update or documentation regarding this change?

**Comment by dotfield** [comment] 2018-05-09 13:42
It is actually a poor underlying API that you repeat the request with different offsets, assuming that underneath it keeps repeating the query to the database.

What you actually want underneath is an initial request followed by a sequence of requests for more data using a handle that you will have got from the initial request.

There is no guarantee that if you call the same query twice you'll have exactly the same search results, so the offset system isn't even guaranteed to work properly.

The documentation now says 10000 but I don't know what it said before. The documentation also mentions queryFilters and gives a couple of examples but not a proper description of which ones are available and what kind of parameters they take.

tag:new is also flawed. I should be able to request a release date and get everything that was added from that point. Release date is in the metadata. Is release date the same as the date it was made available on Spotify?

I'm also interested only in new music. Not music from the 1960s that has only just made it onto Spotify. Within the last 2-3 months is "new". So when you can finally persuade Slade and the Dave Clark Five to make most of their back catalogue available, it will be very nice but I won't want them in my new release search.

**Comment by hughrawlinson** [comment] 2018-05-10 09:12
Hi @dotfield - sorry to hear you're unhappy with the API. Thanks for the feedback. We'll take it into consideration. For clarity, the documentation has always said 10000, but until a recent change we were allowing further pagination. I'll speak to our team and see if there's a better way to achieve what you're looking for.

**Comment by dotfield** [comment] 2018-05-10 15:41
In the meantime would you please reset the limit to 50000 so I can generate my list.

**Comment by hughrawlinson** [comment] 2018-05-10 16:39
@dotfield unfortunately that won't be possible, the API will now continue to work as it has always been documented - but I'm looking into a way for you to make the query you need in a convenient way, and will update here as soon as I have more information :smile:

**Comment by dotfield** [comment] 2018-05-11 11:46
To start off, a proper documentation on query filters (a table of what is available and what values you can use for them) rather than saying you can use them and a couple of examples.
So when I do tag:new request what other filters am I able to add?

Hopefully that will be your solution as it's clearly better than returning me a lot more results than I actually want.

A handle with a "more" is also better than continually repeating the request, although obviously you'd have to cache my initial search results for a period of time and you may not have the resources to do that.

**Comment by hughrawlinson** [comment] 2018-05-11 17:17
@dotfield yep, I'm trying to get a list of the query filters so that I can document them. Will post here when I get them and can publish them 😄

**Comment by Dyphen** [comment] 2018-05-11 21:34
@hughrawlinson 

Thank you for your response on this issue. Since 2015, I've been using the API to get new, first releases by an artist on Spotify. This was actually first built by Paul Lamere (under Fresh Faces) and worked by: 

1. GET all albums released in the past two weeks using tag:new and offset between 25k-50k
2. Using the artist ID's from those albums, reference database/cache and filter out all known/previous found artists
3. GET all releases from remaining artist ID's and filter out any artist with releases > 1
4. Repeat daily and update app

And this worked great, it's unequivocally the primary reason I pay for a Spotify subscription, up until a week ago. When the limit was changed to 10k, the number of new albums dropped significantly, in some cases completely zeroed out. After testing last week, I reached the conclusion that the artists that fit into this criteria fall after the 10,000 cutoff, due to whatever algorithm is driving the list of albums in tag:new that the request is returning. Less popular artist's albums are on the coattails of this list, and are now unaccessible with the 10k limit. In addition, while using tag:hipster in conjunction with tag:new does remove enough popular artists to get some of the lost artists back on the list, rising artist's first releases are also removed. Many albums found before this update had popularity over 10, and were often some of the best releases.

Because you have stated that the 10k limit is not a bug and will not be reverted, **there is no way from my understanding of the current API to fix this**. However, it should be noted that this singular method of attaining these albums is also not efficient to the API or requests. It's borne out of necessity due to the lacking ability to refine requests beyond an arbitrary two weeks, and the lack of sorting control for query responses. 

For example, if tag:new or a new analogous tag could refine releases to within 1 day, under the assumption that less than 10k albums are added to the Spotify catalogue daily, then the lack of sorting would not matter, as all albums would be captured and filtered accordingly. 

Comparing pre-10k and after-10k numbers:

In 09/2016: **6161** out of 33,281 found.
In 05/2018: **191** out of 10,000 found.

It is a great shame that so many uses have been broken by this fix. I would appreciate any insight on how this could be remedied and accomplished in an alternative fashion. Thank you for your time.

**Comment by dotfield** [comment] 2018-05-14 09:44
There are multiple websites / apps that publish new releases on Spotify and will want to get more than 10,000 results if that's how many new releases there actually are.

I second the above that part of this problem is tied to tag:new which always returns 2 weeks of results. If instead you let us set the start and end-date parameters that would already allow us to "split" this and run the query more frequently rather than once.

I guess though that doing two runs, one without tag:hipster and one with, and I'll get more results than I do now.

**Comment by Dyphen** [comment] 2018-06-12 00:34
Any update on this?

**Comment by jdelgadodonas** [comment] 2018-07-14 09:53
@hughrawlinson Any news? It's quite absurd to have a tag:new search showing there are over 50k results and only being able to get the first 10K.

**Comment by tomaculum** [comment] 2018-07-29 14:30
@hughrawlinson any update regarding this issue?

And did anyone found a better workaround for this than the mentioned alphabetical search query here: #61?

As @jdelgadodonas mentioned, it is absurd to query 200*(26+10) highly overlapping requests to get the results..

**Comment by arirawr** [comment] 2018-09-17 14:11
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.

**Closed by arirawr** 2018-09-17 14:11 UTC
Labels: documentation

**Comment by Dyphen** [comment] 2018-09-17 17:39
@arirawr The people afflicted by this issue are putting more strain on the API than ever before. It is incredibly inefficient to ping 40x as many requests to receive orders of magnitude more overlapping requests than what is sought. All while this could be fixed without ever changing the offset limit, as denoted in potential solutions above. I do not understand how the solution at Spotify is to make things more inefficient for all parties involved.

**Comment by tomaculum** [comment] 2018-10-22 16:34
@hughrawlinson any updates on the list of query filters since the `tag:new` & `tag:hipster` field filters do not work currently?

**Comment by davejhahn** [comment] 2019-01-01 17:51
This does not return the expected results. For example. for 2019, as of right now, there are 2421 albums that have "A" in the title (I know because I ran the full search with 2019-2019 and determined the count of the results with "A" in the title), however, if you query for "A" and 2019-2019, it returns 148.

148 total:
https://api.spotify.com/v1/search?q=a+year:2019-2019&type=album

It appears that search doesn't simply return all results with the letter "A" in it. The documentation for search isn't very good, so it may be that something else needs to be done.

This to me means that there is no way, as of today, with the offset limitation of 10,000, to get the proper list of new releases after the total reaches 10,0000.

**Comment by Dyphen** [comment] 2019-01-03 04:33
> Limiting the searches / breaking down to smaller results, such as a, b, c, does not return the expected results. For example. for 2019, as of right now, there are 2421 albums that have "A" in the title (I know because I ran the full search with 2019-2019 and determined the count of the results with "A" in the title), however, if you query for "A" and 2019-2019, it returns 148.
> 
> 148 total:
> https://api.spotify.com/v1/search?q=a+year:2019-2019&type=album
> 
> It appears that search doesn't simply return all results with the letter "A" in it. The documentation for search isn't very good, so it may be that something else needs to be done.

Hi @davejhahn, just to clarify - were you looking to find albums that have the word "a" in it, or the letter "a", i.e.,

word a example: `**A** Foggy Night`
letter a example: `Sunny d**a**y`

Because that search query will only return albums with the word "a" in it.

**Comment by davejhahn** [comment] 2019-01-03 05:46
@Dyphen  - not searching for words but the letter, with the suggestion that was posted in a related issue https://github.com/spotify/web-api/issues/61#issuecomment-115154442 posted by @thelinmichael

Took a look at a sample search I did, and what you are describing is not exactly the behavior I see.  It seems to match the letter in any part of the artist name but only letters as words (or scenarios like D'Argent) for the album name, which I didn't even realize it was searching both since I have it set to type=album... it looks like I need to use a field filter, regardless it doesn't seem to work the same for all attributes.  

Based on this, it looks like I could use a field filter to the artist, since that does match any occurrence of a single letter, but then I'd have to get the albums and filter to the release_date I'm looking for, which sounds pretty intensive since I'm look at their old releases also, although I'm sure I'm not thinking as efficiently as it could be done.

After looking  at this further, I'm thinking the "new" tag will work for my purpose, since I'm not going back in time (I'm running it daily).  For 1/1/19 and 1/2/19 the total new albums are 1135, but based on what I've seen in the past, I think there was a number a lot higher on the first of the year (1042 for 1/1/19 vs 93 for 1/2/19), which I'm assuming is not the norm...although it seems a lot higher on Fridays also.  So if Fridays and the New Year are ~ the same, say 2100 for two Fridays in a 14 day period, that leaves the remaining 12 days to 658 a day which I think all would be under 10,000 all the time because most days don't have anywhere near that, so I wouldn't run into the 10K offset issue.

So I think I have a workaround, unless someone tells me this won't work for some reason I'm not thinking about, which I'm sure is the case....

**Comment by Dyphen** [comment] 2019-01-03 06:59
@davejhahn Been in this boat for a while, so I can illuminate a bit -

If you want to do by letter, you'll want to search `a*`, not `a`

However, you should also know that placement of the wildcard is bugged right now (#1021); I haven't checked but I'm pretty sure you would need to write: 

`https://api.spotify.com/v1/search?q=year:2019-2019+a*&type=album`

instead of 

`https://api.spotify.com/v1/search?q=a*+year:2019-2019&type=album`

In order for it to work properly.

Lastly, `tag:new` returns _all_ albums that have been released in the past two weeks. That's typically around 80k. Unfortunately, you cannot change the way those results are sorted to return. From my experimental observations, their sorting is driven by a function that weights popularity, among other things. Whatever the specifics are, date of release is not a big one. What this means is that, in the hypothetical that only 500 albums come out tomorrow, only a handful will fall within the first 10k limit (the very popular ones), and many of the lesser popular ones will fall outside of the 10k limit, inaccessible to you. 

What you'd have to do is what myself and others have suggested as a woeful workaround - alphabet wildcards, with a ridiculous amount of overlap.

**Comment by davejhahn** [comment] 2019-01-03 14:06
@Dyphen  cool, thanks for the clarification on the wildcard order for the parameters, would not have had any idea and just said it didn't work....just to clarify, "a*" brings back everything with "a" in the album, I don't need "*a*"?   Of course single letters will be too broad additional logic to traverse through smaller combinations when results > 10000.

For tag:new, when you say 80K for 2 weeks, that is for albums or all releases?  I know there are tons of single releases which are the majority of the releases, but I can't believe there are that many album releases, at least its now what I have seen.  Are you saying that type=album is ignored for tag:new?  I must be looking at the type when looping through because I am not picking up the singles, don't have the code at the moment.

**Comment by Dyphen** [comment] 2019-01-03 22:10
@davejhahn 

>  I don't need (asterisk)a(asterisk)? 

Unfortunately, wildcards cannot be used as the first character in a search query (see [docs](https://developer.spotify.com/documentation/web-api/reference/search/search/). Thus, `a*` will only return results that have a word that starts with "a". So with an example albums:

Abbey Road
Magical Mystery Tour
Revolver
Rubber Soul
Sgt. Pepper's Lonely Hearts Club Band
Twist & Shout

You would only need `r*`, `s*`, and `t*` to capture them all. However, `t*` and `s*` are both going to return Twist & Shout. Hence the inefficiency described in this workaround. 

> Of course single letters will be too broad

I've actually run some tests previously - 17/36 alphanumeric characters yielded more than 10k results. These are the popular characters shown below:

![image](https://user-images.githubusercontent.com/6294998/50664115-ff49d900-0f79-11e9-91a0-a5a2890bb4cd.png)
 
> I know there are tons of single releases which are the majority of the releases, but I can't believe there are that many album releases, at least its now what I have seen. 

You are right, there are not that many album release, but unfortunately singles are still categorized as albums. A type=album result will either have the property `album-type: single` or `album-type: album`. So you will get both.

**Comment by shillshocked** [comment] 2019-05-19 23:46
This also doesn't account for non-English results, that may use non A-Z characters in the title. Come on, Spotify, you can do better than this. :)

**Comment by dotfield** [comment] 2019-08-09 12:05
yesterday I ran my usual searches and got virtually no results. Have they
stopped tagging new releases with tag:new or something?
Or was something just broken yesterday?

If the former, how do we get hold of a list of new releases?

**Comment by magnuskrisell** [comment] 2019-08-09 12:38
It seems that right now it only returns 2,000 results, and it there are more than 2,000 it just says the total number is 2,000. Quite useless.

**Comment by tomaculum** [comment] 2019-08-09 16:07
I have opened a new issue since they did not change the maximum offset of 10k to 2k in the docs and therefore I hope this is only a temporary issue. This affects every search query not just` tag:new`. 
#1318

**Comment by Dyphen** [comment] 2019-08-09 18:58
> I have opened a new issue since they did not change the maximum offset of 10k to 2k in the docs and therefore I hope this is only a temporary issue. This affects every search query not just` tag:new`.
> #1318

Hopefully it is temporary. Otherwise, in conjunction with the first time this was reduced to 10k, it's evident that Spotify's solution for managing API load is with a hammer. Counter-productive of course, as the workaround for this one is even more complex, even more stressful on the API, all while being more inefficient and less effective.

**Comment by tomaculum** [comment] 2019-08-27 09:23
With just the `tag:new` query I get 2k albums, with `tag:new AND [a-z]` and `tag:new AND [a-z]*` I get about 30k unique albums and with my current workaround I get 100k results with `tag:new AND [a-z]` and `tag:new AND [a-z]*`  and `tag:new AND [a-z][a-z]` and `tag:new AND [a-z][a-z]*`.

Now I am around 10k api calls for this simple query.

Did anyone find a better workaround or did combine more keywords or field filters?

**Comment by diegocl02** [comment] 2020-04-13 21:28
Guys, one question, how are you managing to get the data from beyond the offset limitation? I'm starting a project in which I'm using the `search` api. Even the response says there were 100k items from my search, I'm not able to reach more than 2k because of the offset limit. Thanks

**Comment by davejhahn** [comment] 2020-04-13 22:37
I do this recursively.  If the results is > 2000, it breaks the search done, until it is not > 2000.

e.g. A -> AA -> AAA
                          AAB
                          AAC -> AACA
                                       AACB
 
And so on.   As the year goes on, it takes longer and longer to complete (think 1-2 hours or more), although I'm sure there is room for some level of efficiency improvements in mine, but it took me a while to get it right so I am hesitant to touch it.

It is an absolute brutal way of doing it, but Spotify, for whatever reason, would rather have exponentially more searches than providing paging capability.

**Comment by magnuskrisell** [comment] 2020-04-14 08:21
Yeah, I haven't found a better way either.

But I have realized recently that most of the good songs have titles in cyrillic, and searching just for those is much quicker!
