### ISSUE TITLE
Spotify client stops syncing (Android & PC)

### ISSUE THREAD

**Issue by AdrielGiannoni** [spotify/web-api#234] opened 2016-05-21 02:47 UTC
I need to know if exists some limitation on adding tracks to a playlist (using WEB API), because im trying to add tracks approximately every three minutes, and after some hours of working property my spotify client doesnt sync anymore. I have to restart spotify client to normalice. Any idea? Im sure that my internet connection is fine. 
Spotify client has some log?
Thanks!

**Comment by thelinmichael** [comment] 2016-05-29 09:14
@AdrielGiannoni, thanks for your report. This is something that needs to be fixed in Spotify's desktop application. Since the Web API is working as intended, I'm closing this issue.

**Closed by thelinmichael** 2016-05-29 09:14 UTC
