### ISSUE TITLE
Missing results on searches with operators AND/NOT

### ISSUE THREAD

**Issue by restfulmt** [spotify/web-api#269] opened 2016-07-26 12:54 UTC
Some results are missing on searches using AND/NOT operators. For instance, the following album is found when searching for “mended” but it is not found when searching for “mended AND with” or “mended NOT with”.

**name: "Mendedagain",
uri: "spotify:album:2Ofy5ANBUHNx4vp7DH37S1"**

**Request 1 (search for “mended”):**
https://api.spotify.com/v1/search?query=Mended&offset=0&limit=50&type=album

albums.total=27
Video with id=2Ofy5ANBUHNx4vp7DH37S1 found

**Request 2 (search for “mended AND with”):**
https://api.spotify.com/v1/search?query=Mended+AND+With&offset=0&limit=50&type=album

albums.total=1
Video with id=2Ofy5ANBUHNx4vp7DH37S1 not found

**Request 3 (search for “mended NOT with”):**
https://api.spotify.com/v1/search?query=Mended+NOT+With&offset=0&limit=50&type=album

albums.total=25
Video with id=2Ofy5ANBUHNx4vp7DH37S1 not found

Am I missing something?

Thanks!

**Comment by asmitter** [comment] 2016-11-11 12:17
Sorry for the late reply on this one. There've been a few improvements to search in the meantime. I tried out the cases you linked to:

https://api.spotify.com/v1/search?query=Mended&offset=0&limit=50&type=album
Return 29 results

https://api.spotify.com/v1/search?query=Mended+AND+With&offset=0&limit=50&type=album
Returns 1 results ("Mended With Gold")

https://api.spotify.com/v1/search?query=Mended+NOT+With&offset=0&limit=50&type=album
Returns 28 results (all of the one in the first result set, minus the one in the second result set).

This looks like expected behaviour, so I'll close this ticket. If you see more related issue, please open a new one.

**Closed by asmitter** 2016-11-11 12:17 UTC
