### ISSUE TITLE
Search users by display name

### ISSUE THREAD

**Issue by TheAtomicGoose** [spotify/web-api#347] opened 2016-11-10 19:02 UTC
I may have just not looked thoroughly enough, but looking through the API endpoints, I don't see any way to search users by display name. Is that possible? If not, could it be added?

Thanks!

**Comment by hughrawlinson** [comment] 2016-11-14 16:13
Hey @TheAtomicGoose - we don't have user search available via the web API at the moment. I'll keep this as a feature request so that we can track demand. Could you let me know a bit about your usecase?

**Comment by TheAtomicGoose** [comment] 2016-11-14 19:28
I'm working on a tool called [Spotifork](https://github.com/TheAtomicGoose/spotifork) (that page isn't fully up to date) that allows people to copy other users' playlists to their own account, and the simplest way for Spotifork users to enter the playlist they're looking to copy is by searching for it in the form `<Playlist, User>`. However, most people aren't going to know that they need to get the playlist owner's user ID rather than simply using the owner's display name, so I'd like to be able to search for possible owners using the  display name that the Spotifork user entered, and then search through the resulting Spotify users' playlists to find the playlist that the Spotifork user is looking to copy.

Sorry, I know that was a somewhat dense explanation...

**Comment by surayashivji** [comment] 2017-02-21 10:45
+1 - Also trying to search by display name which creates collaborative playlists between friends!

**Comment by kasks** [comment] 2017-02-22 02:29
Also wondering if this will be available!

**Comment by JamieHaberman** [comment] 2017-03-02 20:15
Also working on an app that would need this!

**Comment by hughrawlinson** [comment] 2017-03-20 17:37
I realised this is a duplicate of #95 - I'll close this issue as the other is older. Please subscribe to that one for any updates. Thanks for the report!

**Closed by hughrawlinson** 2017-03-20 17:37 UTC
Labels: duplicate, feature request
