### ISSUE TITLE
Missing playlists in Get a List of a User's Playlists endpoint

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#87] opened 2015-07-19 16:06 UTC
Hi,
Here MAGNANO Thomas, from Soundiiz, the playlists converter.
We've got a strange issue when we get playlists of an user.

This is what i call : https://api.spotify.com/v1/users/'id_user'/playlists

We can get all playlists but sometimes... no.
Some users (i can give you name in private), don't have all their playlists returned with this method.
Do you know why ? Scopes are good i suppose  => "playlist-read-private playlist-read-collaborative playlist-modify-public playlist-modify-private" 

It's an issue just for some users but why ? Even if they create a new playlist on the web version, it's not returned in this call.

Thanks a lot for helping us !

**Comment by thelinmichael** [comment] 2015-07-21 12:13
Hi Thomas. This sounds interesting, but it'd help a lot if you could provide us with the username and the playlist URI that isn't returned. Also, I'm assuming that you're making these requests with an access token that's authorized by the user that corresponds to `id_user` in the URL in your issue.

**Comment by thelinmichael** [comment] 2015-07-27 11:30
@blackarcanis, could you double-check that username please?

**Comment by blackarcanis** [comment] 2015-08-09 10:30
@thelinmichael It's possible with a maj case "Etiennepvst" it's a linked account to Facebook.

**Comment by thelinmichael** [comment] 2015-08-10 12:13
@blackarcanis, thanks for clarifying. Spotify doesn't support uppercase characters in user_id's, so the username would be converted to `etiennepvst`, as you posted in your comment 20 days ago. There's no user with that user_id in Spotify, as shown by making a request to https://api.spotify.com/v1/users/etiennepvst, which returns a 404 Not Found response. Making a request to retrieve this user's playlists will return an empty list of playlists.

However, making a request to the Get User's Playlists endpoint for the user with user_id `11895755` will return the list of playlists including the one that you've found missing. (This request is made using an access token not authorized by user `11895755`, with no extra scopes.) 

[API Console link to this request](https://developer.spotify.com/web-api/console/get-playlists/?user_id=11895755)

This means that I can't reproduce the issue you're seeing, unless you're only seeing it when using an access token authorized by this user, with certain scopes. Would appreciate if you'd check again if you're seeing this issue using `11895755` everywhere, instead of `etiennepvst`.

**Comment by blackarcanis** [comment] 2015-08-10 15:25
Ah yes, i can confirm it's good with this ID !
But how can i get this kind of ID ? The only one i've got with the request https://api.spotify.com/v1/me is the username name and not an incremental ID like you have here.

Thanks !

**Comment by thelinmichael** [comment] 2015-08-11 06:38
@blackarcanis, interesting. Could you please paste the response from the `/me` endpoint?

**Comment by blackarcanis** [comment] 2015-08-11 07:23
As example, my account return : 

{
  "display_name" : "Thomas Magnano",
  "external_urls" : {
    "spotify" : "https://open.spotify.com/user/blackarcanis"
  },
  "followers" : {
    "href" : null,
    "total" : 2
  },
  "href" : "https://api.spotify.com/v1/users/blackarcanis",
  "id" : "blackarcanis",
  "images" : [ {
    "height" : null,
    "url" : "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1/v/t1.0-1/s200x200/10277173_10204056221987836_2484803685133355525_n.jpg?oh=c38127b9dc554780437b71bebdb9f218&oe=5648E559&__gda__=1447119500_b601be8e80dab5dfd4d7cde74ea81c8e",
    "width" : null
  } ],
  "type" : "user",
  "uri" : "spotify:user:blackarcanis"
}

There is no numerical ID here.

**Comment by thelinmichael** [comment] 2015-08-11 18:52
Thanks a lot @blackarcanis. If a user has registered their Spotify account through Facebook they're given a numerical ID such as  `11895755`. When you retrieve the data from the `/me` endpoint for this user, the `id` property should be `11895755` and the `uri` should be `spotify:user:11895755`. I suppose my only question mark regarding this is where the username `etiennepvst` comes from.

**Comment by blackarcanis** [comment] 2015-08-11 21:27
I'm not sure to understand.
The fact is this friend can't see this playlist in the listing of his playlists.
He told me "etiennepvst" is the name of his facebook.

And you say "Web API doesn't expose Facebook user id's" so... how can i get it here ? Because there's a connection between Facebook and Spotify and his case.

For my account "blackarcanis", when i connect Spotify to Soundiiz with my Facebook account, it's always "blackarcanis" wich is returned and not an numeric ID...

**Comment by thelinmichael** [comment] 2015-08-12 07:42
@blackarcanis, you're not retrieving a numeric ID because you didn't register your Spotify account through Facebook. Instead, my guess is that you added the Facebook integration as an afterthought. Your friend was given a numeric ID because he never chose a Spotify username. I'm going to try to recreate this again but so far I can't see why that playlist wouldn't be returned since it's public, not collaborative, and owned by the user himself. I'd appreciate if you could paste the response you're getting from the API using this user's credentials.

**Comment by blackarcanis** [comment] 2015-08-12 07:57
Thanks @thelinmichael for your help !
I understand now for Spotify and Facebook.
I will try to get this response with this credentials for tell you.

Just for be more precise : When this user goes to the web player he can't see "Lana Del Rey" playlist but on the software app, he can see it.
And me on Soundiiz i can retrieve all his playlists web but not the playlists he can see on the desktop app.
Pretty strange...

**Comment by blackarcanis** [comment] 2015-08-12 17:32
Here is the return with credentials of the account of my friends : 
{
  "display_name" : "Etienne Pvst",
  "external_urls" : {
    "spotify" : "https://open.spotify.com/user/1176389456"
  },
  "followers" : {
    "href" : null,
    "total" : 5
  },
  "href" : "https://api.spotify.com/v1/users/1176389456",
  "id" : "1176389456",
  "images" : [ {
    "height" : null,
    "url" : "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpt1/v/t1.0-1/s200x200/11206058_458770904285638_6391901812323605103_n.jpg?oh=e57259d3b4f986f29c10dcd5e9e5c382&oe=564E964F&__gda__=1451440690_0f4af45051393a95df7c3e14efc31cb7",
    "width" : null
  } ],
  "type" : "user",
  "uri" : "spotify:user:1176389456"
}

**Comment by blackarcanis** [comment] 2015-08-20 06:13
@thelinmichael , got some some news ? :/

**Comment by thelinmichael** [comment] 2015-08-20 08:11
Ok, this is starting to make sense now.

So what I see here is that your user, Etienne Pvst, has a Facebook generated `id` that's `1176389456`. He is following a playlist made by another user who also has a Facebook generated, which is `11895755`. When you retrieve Etienne's (`1176389456`) playlists, the playlist made by user `11895755`, `spotify:user:11895755:playlist:6QL9M0s6QYjCbtOxOk67Z7`, doesn't show up.

I've checked which playlists user `1176389456` is following, and `spotify:user:11895755:playlist:6QL9M0s6QYjCbtOxOk67Z7` isn't one of them. Therefore, it would make sense that this playlist doesn't show up in Soundiiz.

**Comment by blackarcanis** [comment] 2015-08-20 08:20
Well... the issue is this two accounts it's the same user, a friend of me, and for him he has only one account :/ And that's why he doesn't have the same playlists on the web version and the software version.

Do you have an issue with this migration when you introduce and old user to the web version ?

**Comment by thelinmichael** [comment] 2015-08-21 07:00
@blackarcanis, my assumption is still that these are two different accounts. I'd ask him to log out of the desktop application and log back in again using his Facebook account. I'd also ask him to open a private tab in his browser and try logging into the [Web Player](https://play.spotify.com). If he uses the same Facebook account to log in but still gets different playlist content, it sounds like a bug.

**Comment by thelinmichael** [comment] 2015-11-15 21:29
Closing this issue now since we haven't had any reports of similar problems. Please open it if you're still experiencing this and you believe that this occurs for a single account.

**Closed by thelinmichael** 2015-11-15 21:29 UTC

**Comment by pcevikogullari** [comment] 2015-12-04 14:10
I have the same problem. Although my permissions are set to (user-read-private","playlist-modify-public","playlist-read-collaborative","playlist-modify-private", "streaming"), I cannot get some of my playlists. I do not have numerical id as @blackarcanis .
