### ISSUE TITLE
Long polling or push for /me/player

### ISSUE THREAD

**Issue by tkhduracell** [spotify/web-api#526] opened 2017-05-11 20:25 UTC
Would be super useful to have a mechanism for long polling or subscribing to updates or the player state.

**Comment by dreszczyk** [comment] 2017-05-16 13:35
Probably duplicate of #492

**Comment by seahorsepip** [comment] 2017-06-04 13:17
@arirawr 
I'm currently polling the endpoint every 3 seconds, what about rate limits? 
My app user base can probably considerably grow when it's out of the testing phase and published.

**Comment by asmitter** [comment] 2017-06-08 10:55
Closing as a duplicate of #492 - please add your feedback over there.

**Closed by asmitter** 2017-06-08 10:55 UTC
Labels: enhancement, feature request
