### ISSUE TITLE
Spotify Playlist Request is not up-to-date

### ISSUE THREAD

**Issue by ogmischka** [spotify/web-api#310] opened 2016-09-15 09:01 UTC
Hello guys,

I like to use your Web Api. I use this request to get all informations about the tracks in the playlist:
https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}

What I need is, how often the songs were played, who played them etc.

The point is I am getting this kind of the informations BUT the data is not up-to-date.
All tracks which were added in the past 3 month are not in the request.  ?!?!?

**Comment by thelinmichael** [comment] 2016-09-17 08:31
@ogmischka, trying to break down your ticket into separate parts to get more clarity on what you need.

> What I need is, how often the songs were played, who played them etc.

Information regarding how many times a track has been played and who played them isn't exposed through the Web API.

> The point is I am getting this kind of the informations BUT the data is not up-to-date.

Could you clarify what data isn't up to date? 

> All tracks which were added in the past 3 month are not in the request. ?!?!?

It sounds like you should be using the [Get a Playlist's Tracks](https://developer.spotify.com/web-api/get-playlists-tracks/) endpoint instead of the [Get a Playlist](https://developer.spotify.com/web-api/get-playlist/) endpoint. The latter one will return playlist metadata, but only the first page of tracks.

**Comment by ogmischka** [comment] 2016-09-26 15:05
@thelinmichael thx you for your help.
> Could you clarify what data isn't up to date?

the songs are not in reqest of the playlist.

> It sounds like you should be using the Get a Playlist's Tracks endpoint instead of the Get a Playlist endpoint. The latter one will return playlist metadata, but only the first page of tracks.

I tried it, but I receive the same result as the "get a playlist" endpoint. 
the last added song in the request is from 2016-07-26. in the meantime over 30 new songs were added.…

**Comment by Foldalake** [comment] 2016-09-29 16:06
@ogmischka Have you specified the limit and offset parameters in your request? If the playlist contains more tracks than the limit parameter (default is 20), you need to send more requests to download the complete list, and increase the offset with each request.

Could that be why your new songs don't show up? An easy way to check if your playlist is up to date is to move your new songs to the top of the playlist - will that make them show up in your request?

If this solves your problem, also check out the "next" property in the response. Spotify provides the uri you need to get the rest of the list. Pretty neat! :)

If this is not the cause of your problem, it sounds like your response is cached. To avoid caching issues, perhaps you could provide the etag in the If-None-Match request header.

**Comment by thelinmichael** [comment] 2016-10-15 16:39
Thanks for jumping in @Foldalake, you're asking exactly the questions I'm interested in as well. @ogmischka, if you still believe that things aren't working properly - could you please specify the exact request you're making to the web API and what IDs you're expecting to be in the response? Thanks!

**Comment by thelinmichael** [comment] 2016-12-30 20:02
@ogmischka, I'm closing this issue since it's been a while since the last response. Please reopen it if you're still experiencing this problem.

**Closed by thelinmichael** 2016-12-30 20:02 UTC
Labels: help wanted
