### ISSUE TITLE
500 Internal Error - Deleting Tracks

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/web-api#43] opened 2015-05-07 01:07 UTC
Hi I am getting a 500 Internal Error when attempting to delete songs from a play list. Using the web api on a native Android app. Code is as follows; any ideas? Thanks

mUrl = "https://api.spotify.com/v1/use..." + aUserID + "/playlists/" + aPlayList + "/tracks";

HttpParams httpParameters = new BasicHttpParams();
HttpConnectionParams.setConnectionTimeout(httpParameters, 2000);
HttpConnectionParams.setSoTimeout(httpParameters, 4000);
HttpClient httpclient = new DefaultHttpClient(httpParameters);
HttpResponse response = null;
HttpDelete mRequest = new HttpDelete(mUrl);
mRequest.setHeader("Content-Type", "application/json");
mRequest.setHeader("Authorization", "Bearer " + mCredentials);
try
{
    JSONObject messageBody = new JSONObject();
    JSONArray tracks = new JSONArray();
    for (String track : mFileNames)
        tracks.put("spotify:track:" + track);
    messageBody.put("tracks", tracks);
    byte[] outputInBytes = messageBody.toString().getBytes("UTF-8");
    mRequest.setEntity(new ByteArrayEntity(outputInBytes));
    response = httpclient.execute(mRequest);
}
catch (JSONException e)
{
    e.printStackTrace();
}
catch (UnsupportedEncodingException e)
{
    e.printStackTrace();
}
catch (ClientProtocolException e)
{
    return "@$ - " + e.toString();
}
catch (IOException e)
{
    return e.toString();
}

**Comment by thelinmichael** [comment] 2015-05-07 11:53
Hey @Brad-Jackson. Could you please supply the values for `aUserID`, `aPlayList`, and `messageBody`? It'd help a lot. Best thing would be to recreate the issue using the [Web API Console](https://developer.spotify.com/web-api/console/delete-playlist-tracks/).

**Comment by Brad-Jackson** [comment] 2015-05-08 02:30
I have found my problem in the formatting of the message body. However here is the data so that you can give a better message than a 500 error message.

aUserID = ebrahimnightlife
aPlayList = 02sMFz8nBzzTLKyBWO7ipn
messageBody = {"tracks":["spotify:track:0j0O1QCbDNFAXPyVozJIZn","spotify:track:7wMq5n8mYSKlQIGECKUgTX","spotify:track:5TayOsH85LIq21la1XGt1W","spotify:track:0QCkYWRZo64iY71NxAvOU7","spotify:track:2y4lAQpi5VTNLu2ldeTdUH","spotify:track:6tsMn9okxcLBklFQ2Sc8Ar","spotify:track:3ZgzdVGT8fFOIFq44bJAG9","spotify:track:0gsIQwgHmi1DGv1n2IipUr","spotify:track:6umBH7xHLEU9RVhH4mpXQ3","spotify:track:6CwXryYLf1ZAJZ3rCclEp9","spotify:track:5brMyscUnQg14hMriS91ks","spotify:track:5FeuH4LtGxDWkSkhRG47QT","spotify:track:7wck5ORA8dJB8To9rc10gi","spotify:track:74Hy0E0huf9VS853otOC0m","spotify:track:4VNDr77o8ZJ2mhjys1QXZk","spotify:track:0DiWol3AO6WpXZgp0goxAV","spotify:track:4l2hnfUx0esSbITQa7iJt0","spotify:track:4jOtC832PyIXlCVPRElfQu","spotify:track:41Ng6yrCYnNnmfgubGK24g","spotify:track:0FhhskIAZ5JiNBh2sP7Aza","spotify:track:5xHooj89TQoQHj3dALvSh1","spotify:track:7ksYJ95P5vP87A0GH34CIk","spotify:track:04y7iJXobJhXuxLhC91LAd","spotify:track:77W6VUoJdasCQgjc5DW19q","spotify:track:0tr0D36L1RwPdUTFfyNq37","spotify:track:5OnMFB8DObhaeks5i1ZDdh","spotify:track:2x71TCddP7QTNxl5sblGWM","spotify:track:2LEF1A8DOZ9wRYikWgVlZ8","spotify:track:4pkZNPC6yeMnQABwkTmsR6","spotify:track:7zrYKlgYQv1ELz7LGyjTd1","spotify:track:3mqRLlD9j92BBv1ueFhJ1l","spotify:track:7Hv89f7Dpm5Hce1XkBbjQZ","spotify:track:1YRjRHdl0aEtzHEn1uGi8k","spotify:track:57PjISfyOyDcvTPipz16nf","spotify:track:4yFwM7hqSVz2oDyhgjxK8B","spotify:track:2wNGoon7FlKnVEyYS1ZRBQ","spotify:track:6RcQOut9fWL6FSqeIr5M1r","spotify:track:1stzXCaYomTuSbegXTzYFf","spotify:track:3EYSC3BKjvJA1SleLlR68j","spotify:track:2rJojRundKuKFgbvmCAYva","spotify:track:32Z4ioCoKKsKMFS9vhzkJJ","spotify:track:1o5w5ayh8gZGxdk1agtFT2","spotify:track:5gCotmH9AjDCdKkvvKG6xU","spotify:track:69kOkLUCkxIZYexIgSG8rq","spotify:track:5Sf3GyLEAzJXxZ5mbCPXTu","spotify:track:59lRsVkNO0wWEwm7UUiXrD","spotify:track:11ClKwQKDE4sicKmfzS6PQ","spotify:track:0sooJd5WbNnnz5k6yO7FIQ","spotify:track:2kqAtjOtQPAR0OiYUJR43k","spotify:track:4pq6q25ckZxU8oVRzLI6YJ","spotify:track:4S5b3wwIXpVNvY2jeIQdKu","spotify:track:1JuKmVRi6RHkykqwN7RjF1","spotify:track:0QdX3gmPnAYRWtphOE0ThI","spotify:track:19EQUqnUXEeiBrY10JhPEF","spotify:track:4gTMIyJJlSuB5BOhbMri6B","spotify:track:1AvXB7pTYb7irnDLRfE27H","spotify:track:1d6vQqkVFIAyYTARdO7Ms2","spotify:track:7tklytz84iS8vnUJrBRSVj","spotify:track:2HwlvOkwACOGFySnp16b9l","spotify:track:1ZZYwFDt1nWoDEBbvUKMPP","spotify:track:2zAKjaFeTX0R3j57fTf8Ux","spotify:track:32fmQsWSAaDas2MJRyMSGG","spotify:track:0BdUVxalNsMcrNfLTqK20x","spotify:track:4yHTYyFIG7SRQA1uhO8PyS","spotify:track:4mlJvW3lbChIl0zUl5xS3f","spotify:track:43A8FeaAetF2Imc28DX29I","spotify:track:3k3pMmdnObJC9Pu9RlStlk","spotify:track:3QTAxYe6lTzSpBG4vNoTeL","spotify:track:5j82yGNCjpk6R50LgR4hHG","spotify:track:0vZjr3ZTtqxeNTNU7VgycA","spotify:track:3NlLrNeMGEtzVJITQE2LJI","spotify:track:0GrrLYCH8u81aENhC8FBF4","spotify:track:25bQlUokjsyZ91GvXtLrUb"]}

Here is the  HttpDelete class as there isn't one in Android.
    class HttpDelete extends HttpPost
    {
        public static final String METHOD_NAME = "DELETE";
        public String getMethod() { return METHOD_NAME; }

        public HttpDelete(final String uri) {
            super();
            setURI(URI.create(uri));
        }
        public HttpDelete(final URI uri) {
            super();
            setURI(uri);
        }
        public HttpDelete() { super(); }
    }

**Comment by thelinmichael** [comment] 2015-05-08 07:15
Confirmed it as a bug. It's caused by the way the JSON is formatted in your request. It doesn't adhere to the format the service is expecting (it's missing the `uri` property) and due to a bug it throws an error instead of returning a 400 Bad Request response.

According to the documentation on [Remove Track from Playlist](https://developer.spotify.com/web-api/remove-tracks-playlist/), one of the valid message formats is:

```json
{
  "tracks" : [{
     "uri" : "{track_uri}",
     "position" : "{position}"
  },
  {
     "uri" : "{track_uri}",
     "position" : "{position}"
  }]
}
```

There are other ways of specifying which tracks should be removed, but this is the one closest to what you're specifying.

I'm not closing this bug yet, we should patch the service so that it returns a client error response.

**Comment by thelinmichael** [comment] 2015-05-18 15:14
Fix deployed, closing this issue. Thanks again for raising this @Brad-Jackson!

**Closed by thelinmichael** 2015-05-18 15:14 UTC
Labels: bug
