### ISSUE TITLE
Check if Users Follow a Playlist broken

### ISSUE THREAD

**Issue by johnniepmw** [spotify/web-api#58] opened 2015-05-26 14:53 UTC
The Web Api endpoint to check if a user is following a playlist:
https://developer.spotify.com/web-api/check-user-following-playlist/
appears to be broken.

To reproduce, just use the API Console:
https://developer.spotify.com/web-api/console/get-playlist-followers-contains/#complete

Set Owner Id to digster.ee
Set Playlist Id to 6OS6IJrjzZTB8RLVbAOxAy
Set Spotify User Ids to johnniepmw

**Comment by JMPerez** [comment] 2015-05-26 14:57
@johnniepmw It does seem to work for us. Can you paste the output that you get from the Web API Console? It would help also to determine whether there is an error in the console or in the endpoint itself.

**Comment by johnniepmw** [comment] 2015-05-26 16:41
Thanks for the quick response.  I am able to sometimes get a "false" response from the Api console now, however whenever I log into Spotify in my browser by redirecting the user to say:

https://accounts.spotify.com/authorize?client_id=4432c75d956442158013a14f3977aa55&response_type=token&scope=user-follow-read%20user-follow-modify%20playlist-modify-public%20user-read-email&redirect_uri=http%3A%2F%2Fplayer.socialpromote.co.uk%2Fspotify_landing

and then make the same request to see if I am following the playlist (e.g. with javascript or via the Api Console), it always returns "true", even if I am not following it.

I have attached a screenshot of the api console in case that helps.

![spotify_checkifusersfollowaplaylist](https://cloud.githubusercontent.com/assets/1391133/7817680/74553eda-03ce-11e5-9ec1-9cf8e0c839fa.jpg)


If there any sort of caching going here that I could be failing foul of?

**Comment by JMPerez** [comment] 2015-05-27 08:08
We are trying to find where the problem is. It looks to work ok for us.
Try this:
- Generate a curl request for following, unfollowing and checking the following state.
- Run follow, then check, then unfollow, then check.

This is an example (hiding my access token):

```
$ curl -X PUT "https://api.spotify.com/v1/users/brunomars/playlists/5ctjju5tPKLub2s7uvblNg/followers" -H "Accept: application/json" -H "Authorization: Bearer BQD....08A" -H "Content-Type: application/json" --data "{\"public\":true}"

$ curl -X GET "https://api.spotify.com/v1/users/brunomars/playlists/5ctjju5tPKLub2s7uvblNg/followers/contains?ids=jmperezperez" -H "Accept: application/json" -H "Authorization: Bearer BQD....08A"
[ true ]

$ curl -X DELETE "https://api.spotify.com/v1/users/brunomars/playlists/5ctjju5tPKLub2s7uvblNg/followers" -H "Accept: application/json" -H "Authorization: Bearer BQD....08A" -H "Content-Type: application/json" --data "{\"public\":true}"

$ curl -X GET "https://api.spotify.com/v1/users/brunomars/playlists/5ctjju5tPKLub2s7uvblNg/followers/contains?ids=jmperezperez" -H "Accept: application/json" -H "Authorization: Bearer BQD....08A"
[ false ]
```

If that works this should also work from your browser. The caching policy for these requests is set so the browser doesn't cache their responses.

**Comment by JMPerez** [comment] 2015-05-27 08:18
We have started investigating this and it looks like a bug in our side. We'll keep you informed with the progress of the issue.

**Comment by JMPerez** [comment] 2015-05-28 11:26
@johnniepmw Good news, we have found the issue and deployed a fix. The issue should be resolved, so I will close this for now. Feel free to reopen it if you find any other problem.

Thanks!

**Closed by JMPerez** 2015-05-28 11:26 UTC
Labels: bug

**Comment by johnniepmw** [comment] 2015-05-29 10:06
Sorry it took a few days to reply.  Thanks for sorting out this bug.  We've tested it again here and it looks good now.  Much appreciate the quick turnaround!

**Comment by jimmieeriksson** [comment] 2015-06-25 08:52
I'm afraid there is a problem with this one again. I've been getting Gateway time out the last couple of days.. and I've tried both from work and mobile phone and its the same problem.
Both user and artist have the same problem...
https://developer.spotify.com/web-api/console/get-following-contains/

The last days I've been getting the following answer
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

Any ideas what could be the cause of this?

**Comment by thelinmichael** [comment] 2015-06-25 11:18
Hi @jimmieeriksson! This was caused by an unrelated issue, and was fixed 30 minutes ago.
