### ISSUE TITLE
Feature Request: retrieve geo data of where top fans are

### ISSUE THREAD

**Issue by eyoon7** [spotify/web-api#812] opened 2018-03-07 19:09 UTC
Use Case:
1. Be able to find where an artists top listeners are

**Comment by hughrawlinson** [comment] 2018-03-30 11:39
Hi @eyoon7 - could you clarify your use case? Once you've found where an artist is most popular, what would you use that data for?

**Comment by eyoon7** [comment] 2018-03-30 17:32
We are doing a little school project where we want to do analysis on how
emerging artists popularity may change as they gain more followers/fans.
For example, if an emerging artist is from Austin, Texas, does popularity
spread outward from Texas? or does the spread of popularity not depend on
proximity to the artists hometown.

**Comment by hughrawlinson** [comment] 2018-05-10 18:08
Thanks for the clarification @eyoon7 :) I'll keep this issue open as a feature request :)

**Comment by arirawr** [comment] 2018-09-21 11:57
Hey there - I'm closing this as a duplicate of #188. Please see the comment on that issue.

**Closed by arirawr** 2018-09-21 11:57 UTC
Labels: suggestion
