### ISSUE TITLE
Expose 'verified' artists in API response

### ISSUE THREAD

**Issue by danwani** [spotify/web-api#419] opened 2017-02-01 21:43 UTC
Feature request

I've checked various endpoints in the API reference (/search & /artists/{id}), and cannot see the 'verified' value getting passed back in the returned data.

Is there any way to access this data point?
Additionally, is there any way to use it as a search filter, so that in searching I only retrieve verified artists?

**Comment by reinierbutot** [comment] 2017-02-15 11:54
:+1:

**Comment by hughrawlinson** [comment] 2017-03-20 14:45
@danwani can you tell me a bit more about your use case please?

**Comment by hughrawlinson** [comment] 2017-03-20 17:05
[Spotify Artist Verification](https://artists.spotify.com/faq/verification#what-is-verification) works by tying an artist's user account with their artist profile. Therefore, this issue is a duplicate of #10, so I'll close this issue and write any updates on that issue.

**Closed by hughrawlinson** 2017-03-20 17:05 UTC

**Comment by danwani** [comment] 2017-03-20 23:57
My apologies, this is a duplicate of #10. 
@hughrawlinson the usecase is the same as one noted in that issue, where we want to validate users of our system as the real artists to allow them extra privileges.
