### ISSUE TITLE
/v1/me/player/play does not log the album context

### ISSUE THREAD

**Issue by seahorsepip** [spotify/web-api#567] opened 2017-06-04 01:13 UTC
Issue found on June 4th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/play `

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Use /v1/me/player/play to start playback of a track in a user's album
2. Get playback info from currently-playing endpoint

#### Expected behaviour:
A context value other then null.

#### Actual behaviour:
Context is null.

**Comment by seahorsepip** [comment] 2017-06-04 01:14
Probably related to: https://github.com/spotify/web-api/issues/522

**Comment by asmitter** [comment] 2017-06-08 07:29
Thanks for the report.
Can you share the parameters you are sending to the `/player/play` endpoint please?

**Comment by richoakley** [comment] 2017-06-08 08:27
Yeah, same issue as #522

**Comment by arirawr** [comment] 2018-08-07 08:56
Hey there, thanks for reporting! This is a duplicate of #522, so please follow that issue for updates.

**Closed by arirawr** 2018-08-07 08:56 UTC
