### ISSUE TITLE
Retrieve number of listeners of an Artist

### ISSUE THREAD

**Issue by tandem-it** [spotify/web-api#130] opened 2015-11-01 23:27 UTC
Is there a way (currently or planned for future versions) to get the information listed in the new "about" tab of an artist on the number of monthly listeners using the spotify web API?

Thanks for your help!
Thanh.

**Comment by thelinmichael** [comment] 2015-11-02 08:32
Hi @tandem-it! No, it's not possible to retrieve most of this information through the Web API.

For future reference, this information is:
- Number of monthly listeners for an Artist
- Top five cities where users listen to the Artist
- Number of followers (Available using the [Get Artist endpoint](https://developer.spotify.com/web-api/get-artist/).)
- A number of Playlists where the Artist is represented

**Comment by aurels** [comment] 2015-11-06 13:40
Hi,

That would be very useful to get the number of monthly listeners for a given artist, just like the followers ;-)

Cheers,
Aurels

**Comment by torres007** [comment] 2016-03-23 17:32
+1 I am also interested in getting the top five cities where listeners are located.

**Comment by TheLucasMoore** [comment] 2016-06-02 00:18
Hey I would love to have this information as well. Along with the number of streams for a specific track.

**Comment by oalders** [comment] 2016-06-02 22:25
@TheLucasMoore you could add a "thumbs-up" to the top comment on https://github.com/spotify/web-api/issues/70

**Comment by loganbentley** [comment] 2016-07-26 14:51
I would also love a way to get data on monthly listeners of an artist.

**Comment by yiqinfu** [comment] 2017-04-17 07:41
Would love to get monthly listener info! Thanks.

**Comment by lunax28** [comment] 2018-02-07 13:32
Any update on this? I too would love to see this feature on the api.

**Comment by Stegoo** [comment] 2018-03-12 09:36
@thelinmichael, any update? It would be pretty useful :)

**Comment by ToddOwen** [comment] 2018-06-20 21:11
Update?

**Comment by usrbowe** [comment] 2018-06-25 03:54
This issue is duplicate of this: #188

**Comment by arirawr** [comment] 2018-09-21 11:52
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.

**Closed by arirawr** 2018-09-21 11:52 UTC
Labels: suggestion

**Comment by iamsreeju** [comment] 2018-10-25 17:37
We can, but not through web API. Place the Spotify login button, go though Oauth and get the token. Then make following curl call after replacing bearer token below. You can find same from n/w calls after login from the app. If you copy curl call from that can see the results. Not a straightforward option anyway.

curl 'https://spclient.wg.spotify.com/open-backend-2/v1/artists/1uNFoZAHBGtllmzznpCI3s' -H 'pragma: no-cache' -H 'origin: https://open.spotify.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' -H 'authorization: Bearer BQDFY4jGj6uDFaqk5z2dycnSr7V5Hji1k0iMqdydhSqVPbxILBGqVgwmGiROJseOduKkS8Kc1vGA-TJgoFBwVAz8f9MzSI8tE5yx7dQjjNuSCoDnVoSTqwB7ZEzx61zUUeLSAzTQCXOxFUhVd9c-B-VOfrBoL7xbf0VKylWrbRDCoq2x02ip-8BOapJHOJS3yZLFlFjOyl2dDV8N_dVyRvSkLxYRLjkC6ojUiwN7tKzWE2iDyyjfKGjVA5RrSJ9VDdpYW4_XYnh0q6BqZrp0_Q' -H 'accept: application/json' -H 'cache-control: no-cache' -H 'authority: spclient.wg.spotify.com' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36' -H 'referer: https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s' --compressed

**Comment by iamsreeju** [comment] 2018-10-25 17:39
> Is there a way (currently or planned for future versions) to get the information listed in the new "about" tab of an artist on the number of monthly listeners using the spotify web API?
> 
> Thanks for your help!
> Thanh.

We can, but not through web API. Place the Spotify login button, go though Oauth and get the token. Then make following curl call after replacing bearer token below. You can find same from n/w calls after login from the app. If you copy curl call from that can see the results. Not a straightforward option anyway.

curl 'https://spclient.wg.spotify.com/open-backend-2/v1/artists/1uNFoZAHBGtllmzznpCI3s' -H 'pragma: no-cache' -H 'origin: https://open.spotify.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' -H 'authorization: Bearer BQDFY4jGj6uDFaqk5z2dycnSr7V5Hji1k0iMqdydhSqVPbxILBGqVgwmGiROJseOduKkS8Kc1vGA-TJgoFBwVAz8f9MzSI8tE5yx7dQjjNuSCoDnVoSTqwB7ZEzx61zUUeLSAzTQCXOxFUhVd9c-B-VOfrBoL7xbf0VKylWrbRDCoq2x02ip-8BOapJHOJS3yZLFlFjOyl2dDV8N_dVyRvSkLxYRLjkC6ojUiwN7tKzWE2iDyyjfKGjVA5RrSJ9VDdpYW4_XYnh0q6BqZrp0_Q' -H 'accept: application/json' -H 'cache-control: no-cache' -H 'authority: spclient.wg.spotify.com' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36' -H 'referer: https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s' --compressed
