### ISSUE TITLE
Ability to add songs to the listener's queue

### ISSUE THREAD

**Issue by Twister1002** [spotify/web-api#170] opened 2016-02-19 03:43 UTC
I would like to request a way to use the Play Queue. I am trying to develop an application where I could make a music jukebox and add people's songs to the Play Queue. This would be a great thing for streamers and such.

**Comment by thelinmichael** [comment] 2016-03-05 10:22
Closing this as it's covered in #15.

**Comment by jhass** [comment] 2017-08-10 11:50
Looks like #15 was closed with only playback control added or am I missing something? If not I guess this should be reopened.

**Comment by MichaelMallett** [comment] 2017-09-07 00:28
@thelinmichael P;ease reopen this, as #15 does not cover this functionality, there is no add to queue functionality listed there.

**Comment by martlind** [comment] 2017-09-08 08:03
+1 to reopen

**Comment by ryantrappy** [comment] 2017-09-10 21:59
+1 to reopen

**Comment by tikotus** [comment] 2017-10-06 07:01
I was really looking forward for #15 to add this but it didn't.
I need this functionality so bad!

**Comment by ski7777** [comment] 2017-11-04 14:48
Wats the state? When to expect a queue API?

**Comment by tegillis** [comment] 2017-12-02 17:32
+1

**Comment by deb42** [comment] 2017-12-07 09:36
+1

**Comment by daniel-centore** [comment] 2018-01-03 04:47
This looks like a duplicate of #462

**Comment by arirawr** [comment] 2018-01-03 09:13
I'm going to close this issue as a duplicate of #462, which appears to have more discussion. We will post any updates to this issue over there!

**Closed by arirawr** 2018-01-03 09:13 UTC
