### ISSUE TITLE
Enable search for User type

### ISSUE THREAD

**Issue by KramerLewis** [spotify/web-api#926] opened 2018-06-27 02:31 UTC
## Use case: 
Search for users by username, name, user id. 

This would enable us to build applications that allow users to find other users without asking them to go to the spotify app and return with the user id.. This and the third most commended feature request issue https://github.com/spotify/web-api/issues/4 would be nice.

## Links:
* https://developer.spotify.com/documentation/web-api/reference/search/search/
  * only supports types: album , artist, playlist, and track
* https://github.com/spotify/web-api/issues/4

**Comment by arirawr** [comment] 2018-06-27 12:08
Hi @KramerLewis - this sounds like a duplicate of #95. You can follow that issue for updates. :)

**Closed by arirawr** 2018-06-27 12:08 UTC
