### ISSUE TITLE
Users Playlists - returns incorrect list

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/web-api#74] opened 2015-06-23 01:28 UTC
This is a strange one. I am building 2 iOS apps, which use the same spotify code. If I login with the user ebrahimnightlife both apps work correctly. However if I login as mr.bungle72 one app returns 12 playlists (which is correct) and the other returns one 1.

Here is the code I am using for the web API call to get the users play lists

**aCredentials** = @"BQCHeK8G-8hEiO6TCe4sdCbCoahZRhLPSrjOpJTGzXfHIC_4UWT9OIGt6n6bPbeyU1IybzSRy_M49sSOdYV1lXEAz8IPAxCEIYqkkIQ0V_-WkkmQGd-VA4s69DOaXWwyyp345p2gLDgEBzRw02u08Q"
**aUserID** = @"mr.bungle72"

```
@implementation HttpSpotifyUserPlayLists

static NSString *gBaseURL = @"https://api.spotify.com/v1/users/";

+ (void)requestUserPlayLists:(NSString *)aCredentials userID:(NSString *)aUserID offset:(NSInteger)aOffset callback:(void (^)(NSDictionary *))aCallback
{
    NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"%@%@/playlists?limit=50&offset=%ld", gBaseURL, aUserID, (long)aOffset]];
    
    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
    
    [request setHTTPMethod:@"GET"];
    [request addValue:[NSString stringWithFormat:@"Bearer %@", aCredentials] forHTTPHeaderField:@"Authorization"];
    
    NSOperationQueue *queue = [[NSOperationQueue alloc] init];
    
    [NSURLConnection sendAsynchronousRequest:request queue:queue completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError)
     {
         NSDictionary *callBackData;
         if (connectionError != nil)
         {
             callBackData = [[NSMutableDictionary alloc] init];
             [callBackData setValue:[connectionError description] forKey:@"Error"];
         }
         else
         {
             NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *) response;
             if ([httpResponse statusCode] != 200)
             {
                 callBackData = [[NSMutableDictionary alloc] init];
                 [callBackData setValue:[NSNumber numberWithLong:[httpResponse statusCode]] forKey:@"Error"];
             }
             else
             {
                 NSError *error;
                 callBackData = [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:&error];
             }
         }
         
         if (aCallback)
             aCallback(callBackData);
     }];
}

@end
```

The only different between the apps is the client id.
Thanks

**Comment by Brad-Jackson** [comment] 2015-06-23 01:42
I have found the reason for the problem. I had the version 8 beta iOS SDK, and the login process was different for it (I recently updated to 9 beta). The user permissions where set on the old version, and not set on the new version.

So the bug for the web API is that it was returning a playlist and not returning a 403 error.

**Comment by jsimonsson** [comment] 2015-06-23 07:41
Hi

I'm glad you found the issue.
It do not think it is a bug that you get back one playlist, you can always retrieve public playlists of other users. So, my guess is that 1 playlist is public out of those 12.

**Comment by thelinmichael** [comment] 2015-06-24 07:11
Closing this issue since this is expected behaviour (double-checked with the playlist system to confirm the number of public playlists). 

Retrieving a user's playlists will never return private playlists unless 
- the access token is authorized by the the same user,
- the access token contains the `playlist-read-private` scope.

**Closed by thelinmichael** 2015-06-24 07:11 UTC
