### ISSUE TITLE
Get-artists always returns followers->count of `0`.

### ISSUE THREAD

**Issue by simonfyi** [spotify/web-api#624] opened 2017-07-27 07:39 UTC
Issue found on the great morning of July 27th 2017.

#### Endpoint(s):
* `GET /v1/artists/{id}`

#### Scope(s):
* No specific, only using an OAuth Token

#### Steps to reproduce:
1. Go to https://developer.spotify.com/web-api/console/get-artist/
2. Get OAuth Token
3. Fill in artist id e.g. `23fqKkggKUBHNkbKtXEls4`
4. Try it
5. See response with `followers->total` of `0`.

#### Expected behaviour:
Show the real followers count, worked like a charm last till night.

#### Actual behaviour:
200 OK response with incorrect data.

#### Screenshot of response

<img width="889" alt="api" src="https://user-images.githubusercontent.com/1185974/28659963-7b160b42-72b1-11e7-8131-177f7c986d83.png">

**Comment by simonfyi** [comment] 2017-07-27 07:48
Update:

It's working properly again.
Will keep the ticket open tho', I wonder if it happens more often.

response right now:

`"followers" : {
    "href" : null,
    "total" : 1743670
  },`

**Comment by arirawr** [comment] 2017-07-27 09:39
I'm going to close this as we are not able to reproduce. However, if you see this again, please let us know!

**Closed by arirawr** 2017-07-27 09:39 UTC
