### ISSUE TITLE
Authorization page: Failed to open page

### ISSUE THREAD

**Issue by nicolasanjoran** [spotify/web-api#1440] opened 2020-01-21 18:49 UTC
Issue found on January 21st 2020.

#### Endpoint(s):
* https://accounts.spotify.com/authorize

#### Scope(s):
* any, even the https://accounts.spotify.com/authorize url redirects to a bad url.

#### Steps to reproduce:
1. Open any Spotify web app that needs authorization from an EU location (eg. [https://developer.spotify.com/community/showcase/playlist-souffle/](https://developer.spotify.com/community/showcase/playlist-souffle/))
2. Click Login

#### Expected behaviour:
The Authorization page shows up

#### Actual behaviour:
Server not found after being redirected to https://login/?continue=.....

I've tried to use a VPN located in the US, it works fine

**Comment by cosst** [comment] 2020-01-21 20:34
We're seeing this too, as of today.

**Comment by nicolasanjoran** [comment] 2020-01-22 08:54
The bug is still not fixed as of now. 
For some reason, it did start to work again on one of my devices. I tried to flush the DNS cache and website data again, the issue reappeared.

**Comment by sukezane** [comment] 2020-01-22 09:55
I have same issue too in Japan.
As far as I know, this problem occurred on ios devices.

**Comment by nicolasanjoran** [comment] 2020-01-22 10:09
@sukezane I experience the issue on macOS (Safari) too.

**Comment by joshubrown** [comment] 2020-01-22 10:42
Thanks for reporting this, folks. We're looking into the cause on our side. I will share an update in this thread soon.

**Comment by joshubrown** [comment] 2020-01-22 11:18
We have deployed a fix for this bug. If you are still seeing this issue after clearing cache, then please comment here and let us know 🙂

**Closed by joshubrown** 2020-01-22 11:18 UTC
