### ISSUE TITLE
Failed Spotify auth using Facebook Messenger as browser

### ISSUE THREAD

**Issue by alexanderkonrad** [spotify/web-api#287] opened 2016-08-13 11:10 UTC
Hi folks,

if I get a link with an Spotify auth link using the Facebook Messenger app (iOS) then the first page looks fine (where you can choose to login directly with your Spotify credentials or using the Facebook authentification) BUT when I try to use the FB auth function the next page will be blank and is unable to load.

So in fact I can't use FB auth within the FB Messenger when trying to create a Spotify authentification. That's pretty frustrating as it works all fine when using a regular desktop web browser..

Regards,
Alex

**Comment by thelinmichael** [comment] 2016-10-16 11:22
Thanks for raising this @alexanderkonrad - and apologies for not responding earlier. (Now I see why you raised the question of this being an official repository during yesterday's API workshop! ;-) 

I can't recreate this issue unfortunately, the Facebook login flow is working fine for me when following a link in Facebook Messenger on iOS. Would you mind trying it out again?

**Comment by mmontag** [comment] 2016-11-10 21:30
@alexanderkonrad I have a little experience with the auth flow inside Messenger - can you explain your use case with a little more detail? Are you using the authorization code flow or implicit flow? What is your redirect URI?

**Comment by alexanderkonrad** [comment] 2016-11-17 13:37
Hi @thelinmichael and @mmontag,
thanks for reply! Happy that this is the official Spotfy channel :)

I've created some screenshots and put them together with some errors. I hope that clarify things..

Basically it is a Spotify Authorization using Facebook authorization all happening within the iOS FB Messenger app.

![Image of problem] (http://alexkonrad.de/upload/spotify_ios_fb_messenger.png)

**Comment by alexanderkonrad** [comment] 2016-11-17 13:38
To add: This all works totally fine using a deskop browser!

**Comment by alexanderkonrad** [comment] 2016-12-27 11:40
Hi @thelinmichael and @mmontag, did you maybe already get the chance to look into this again? Let me know if my screenshots aren't comprehensive! Cheers Alex

**Comment by mcpenchel** [comment] 2017-08-21 22:05
I'm with basically the same problem. When I'm using an iPhone, open the facebook mobile application and click on a link of a website that contains the spotify login button, the redirect sends me to a blank page.. Doesn't work as it should.

The weird thing is: it works on every other situation. Android -> Facebook -> Click; iPhone -> Safari -> Website; Desktop -> Facebook -> Click; .. and so on.

**Comment by arirawr** [comment] 2018-01-22 12:49
Hello from the future! Looks like this has been fixed, as I'm unable to reproduce it with a current version of Messenger. I'm going to go ahead and close the issue 🙂

**Closed by arirawr** 2018-01-22 12:49 UTC
Labels: bug
