### ISSUE TITLE
Scopes in Authorization URL Have No Effect

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [spotify/web-api#1053] opened 2018-10-09 06:17 UTC
Adding scopes to the authorization URL seem to have no effect for my apps.

#### Scope(s):
* Example URL: https://accounts.spotify.com/en/authorize?client_id=c03e26cfbef44692bb8176c73b628569&response_type=code&redirect_uri=https:%2F%2Fauth.musicblobs.com%2Fapi%2Fauth%2Fspotify&scope=user-library-modify&state=some-state-of-my-choice

#### Steps to reproduce:
1. Go to URL above

#### Expected behaviour:
Page should display something that says, "This app will be able to modify your user library."

**Comment by jscholes** [comment] 2018-10-09 08:31
When I visit the example URL, I see that this app will be able to "Manage your saved tracks, albums, and shows".

**Comment by bih** [comment] 2018-12-28 17:54
Hello,

From our systems, it looks like everything should work as expected. I confirmed by clicking the link that I have the same view as @0xNF and @jscholes. As this is resolved, I'm going to close this - but feel free to open a new ticket if you're continuing to have issues.

**Closed by bih** 2018-12-28 17:54 UTC
