### ISSUE TITLE
playing a playlist does not update the playing queue when new songs are added

### ISSUE THREAD

**Issue by sevi-l** [spotify/web-api#798] opened 2018-02-22 13:31 UTC
Issue found on February 22th 2018.

#### Endpoint(s):
* `PUT https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* user-read-email playlist-read-private playlist-modify-private playlist-modify-public user-read-playback-state user-modify-playback-state

#### Steps to reproduce:
1. call the endpoint with a valid user & playlist like so:
body: {'context_uri': 'spotify:user:' + user + ':playlist:' + playlistId}
2. observe on the playing app (on any system) that all the songs are added to the playing queue.
3. add a song either in the app or thru the web api.
4. observe that the song is added to the playlist, but not to the playing queue.

If the play command is issued in the App with the play button, the queue receives all the new songs added to the playlist. In other words, it syncs with the playlist while playing.

#### Expected behaviour:
The playing queue is kept up-to-date when adding a new song to the playlist. (Same behaviour as when playing is started in the app)

#### Actual behaviour:
The playing queue only contains songs that were in the playlist at the time of the play command.

**Comment by arirawr** [comment] 2018-02-22 13:35
Hey @sevi-l ! Thanks for the report. This looks like a duplicate of #537, so you can follow that issue for updates.

**Closed by arirawr** 2018-02-22 13:35 UTC
