### ISSUE TITLE
PUT /me/following endpoint silently fails when using access tokens from my application

### ISSUE THREAD

**Issue by elsbree** [spotify/web-api#109] opened 2015-09-14 20:37 UTC
When I make requests to the /me/following endpoint with access tokens generated with my application's Spotify ID/Secret pair, the requests do not work. The responses have a 204 status code, as is expected, but the users are not actually being followed. If I make the exact same request, but use an access token generated from the API console, I receive the exact same 204 response, but the users are followed successfully.

Is there something wrong with my application's registration with Spotify, or am I on some sort of blacklist? These API calls have been functioning just fine, but in the past few days this issue popped up and now I can't follow people on Spotify through my application.

Here's a sample request:

```
app git:(master) curl -X PUT "https://api.spotify.com/v1/me/following?type=user&ids=stravymusic" -H "Accept: application/json" -H "Authorization: Bearer <Token from Spotify API Console>" -v
*   Trying 193.235.203.195...
* Connected to api.spotify.com (193.235.203.195) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.spotify.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> PUT /v1/me/following?type=user&ids=stravymusic HTTP/1.1
> Host: api.spotify.com
> User-Agent: curl/7.43.0
> Accept: application/json
> Authorization: Bearer <Token from Spotify API Console>
>
< HTTP/1.1 204 No Content
< Server: nginx
< Date: Mon, 14 Sep 2015 20:24:20 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Keep-Alive: timeout=600
< Cache-Control: private, max-age=0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 604800
< Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000;
<
* Connection #0 to host api.spotify.com left intact
```

After the above request, I am following the user in question if I refresh their profile page through the Spotify web client. Then, I unfollow them and make the following request:

```
app git:(master) curl -X PUT "https://api.spotify.com/v1/me/following?type=user&ids=stravymusic" -H "Accept: application/json" -H "Authorization: Bearer <Token from My Application>" -v
*   Trying 193.235.32.166...
* Connected to api.spotify.com (193.235.32.166) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.spotify.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> PUT /v1/me/following?type=user&ids=stravymusic HTTP/1.1
> Host: api.spotify.com
> User-Agent: curl/7.43.0
> Accept: application/json
> Authorization: Bearer <Token from My Application>
>
< HTTP/1.1 204 No Content
< Server: nginx
< Date: Mon, 14 Sep 2015 20:24:52 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Keep-Alive: timeout=600
< Cache-Control: private, max-age=0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 604800
< Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000;
<
* Connection #0 to host api.spotify.com left intact
```

I refresh the user's profile page again, and I'm not following them. I've repeated this test multiple times with the same result. The only difference between the above requests is the IP address of api.spotify.com, but even when the IP address is the same, the issue still occurs.

**Comment by elsbree** [comment] 2015-09-14 21:01
As an update to this: I found that if I get a new Spotify access token by going through the Spotify OAuth flow again, the follow request works. This leads me to believe that maybe the access token I was trying to use before was expired, but the API wasn't telling me that was the case.

Is it possible that the API is incorrectly returning 'success' responses for tokens that are actually expired?

**Comment by thelinmichael** [comment] 2015-10-01 15:04
Thanks for the detailed report @elsbree, apologies for the delayed reply. I don't believe that this is caused by expired tokens being silently ignored by the Web API as that haven't happened previously - not saying that it couldn't occur due to some very rare edge cases.

My first suspicion was that the desktop application caches the following state, and isn't updated since the cache hasn't expired. However, since you see changes in the desktop client's view immediately after using an access token from the API console, that doesn't seem to be the case.

Could you please double-check that the request you're making from the API Console and your application is made on behalf of the same user? Could you also make sure that the access token used by your application has been given the appropriate scope - `user-follow-modify`?

**Comment by albertofortin** [comment] 2015-11-07 00:31
Hello, I'm having similar problem for the same API, /me/following silently fails returning an empty array of artists. But it only fails sometimes, with apparently no reason.

I've tried the same page, same code, with different browsers and I'm getting different results, in a very strange way:
it works on Chrome, IE, Edge; doesn't work on Firefox (even clearing the cookies and going through the OAuth again).

Tried on mobile, got an empty array from Chrome for Android, then tried with an incognito tab and I got the artists I wanted.

**Comment by boriskol** [comment] 2015-11-09 21:07
Have same issue as all above user-follow-modify https://api.spotify.com/v1/me/following? always return error 401 No token provided  DENIED - The requested resource requires user authentication

 var baseUrl = 'https://api.spotify.com/v1/me/following?type=artist&ids=' + artistSpotId;
        var config = {
            headers: {
                'Authorization': 'Basic ' + $scope.accessToken,
                'Accept': 'application/json;'
            }
        };
       
        $http.put(baseUrl, config
        }).success(function (data, status, headers, config) {
                	
                
        }).error(function (data, status, headers, config) {
                    console.log(data);
                    console.log(status);
                    console.log(headers);
                    console.log(config);
                });

**Comment by exstac** [comment] 2015-11-09 21:17
The access token needs to be passed with the Bearer and not Basic as Authorization type.
I.e. 'Authorization': 'Bearer ' + $scope.accessToken in your example above

**Comment by boriskol** [comment] 2015-11-09 21:20
Thank you                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Oscar VestlieSent: Monday, November 9, 2015 4:17 PMTo: spotify/web-apiReply To: spotify/web-apiCc: boris kolaricSubject: Re: [web-api] PUT /me/following endpoint silently fails when using access tokens from my application (#109)The access token needs to be passed with the Bearer and not Basic as Authorization type.
I.e. 'Authorization': 'Bearer ' + $scope.accessToken in your example above

—Reply to this email directly or view it on GitHub.

**Comment by boriskol** [comment] 2015-11-09 22:05
Did not work, getting some error :(

**Comment by asmitter** [comment] 2016-11-06 18:30
Closing this issue as it is almost a year without update and the thread derailed a bit with similar but unique issues.

If anyone on the thread still has an outstanding problem or unexpected error, please create a new issue  with reproduction steps.

**Closed by asmitter** 2016-11-06 18:30 UTC
Labels: bug, help wanted
