### ISSUE TITLE
`available_markets` missing from search results

### ISSUE THREAD

**Issue by loisaidasam** [spotify/web-api#1048] opened 2018-10-04 20:48 UTC
Issue found on 4 October 2018.

#### Endpoint(s):
* `GET /v1/search`

https://developer.spotify.com/documentation/web-api/reference/search/search/

#### Scope(s):
* Authed

#### Steps to reproduce:
Do a search for a song and explicitly pass `market=US` and compare the response to the same search without explicitly passing `market`. The one without `market` has `available_markets` in the response, the one with `market` does not.

#### Example

Using python `spotipy` client's [search method](https://github.com/plamere/spotipy/blob/4c2c1d763a3653aa225c4af848409ec31286a6bf/spotipy/client.py#L333-L344), assuming that `client` is an instance of `spotipy.client.Spotify`:

```python
In [6]: 'available_markets' in client.search(q='isrc:USCM51800206', type='track')['tracks']['items'][0]
Out[6]: True

In [7]: 'available_markets' in client.search(q='isrc:USCM51800206', type='track', market='US')['tracks']['items'][0]
Out[7]: False
```

#### Expected behaviour:
I would expect that both responses should let the user know which markets (including any explicitly passed market) the song is available in. The response where the market is explicitly specified should limit the results to songs ONLY available in that market, but it shouldn't cut out any extra (useful) information.

#### Actual behaviour:
Only the response without explicitly passing a market gets `available_markets` returned.

**Comment by bih** [comment] 2018-12-28 17:56
This is expected behaviour. When you specify a market, it doesn't inform you about which markets the track is available in. And when you don't specify a market, it assumes the user's default market but informs you about all the markets the track is available in.

Closing this as a duplicate of #1025.

**Closed by bih** 2018-12-28 17:56 UTC
