### ISSUE TITLE
Can search be as good as the Spotify app?

### ISSUE THREAD

**Issue by mph070770** [spotify/web-api#268] opened 2016-07-26 08:04 UTC
I believe this issue has been raised before but I don't know if there's an agreed way to get improved results. The web-api is broken for me, if not. 

If I try:
https://api.spotify.com/v1/search?q=adele&type=artist

I get lots of results for artists such as "Robyn Adele Anderson" and "Adele Anthony". Is there a way to ONLY get results for artist=adele?

The Spotify app is very good at handling spelling mistakes, such as:

Ed Sheerun, Ed Sheeron, Ed Shearun etc providing results for "Ed Sheeran"

The web-api just returns empty results. Is there any way to make it make intelligent / forgiving?
https://api.spotify.com/v1/search?q=ed+sheerin&type=artist

**Comment by jscholes** [comment] 2016-07-26 11:20
> If I try:
> https://api.spotify.com/v1/search?q=adele&type=artist
> I get lots of results for artists such as "Robyn Adele Anderson" and "Adele Anthony". Is there a way to ONLY get results for artist=adele?

You can add [&limit=1](https://api.spotify.com/v1/search?q=adele&type=artist&limit=1) to only see the first matching artist, which given her popularity and the way search queries seem to work will most likely always be Adele herself.

But I don't really understand your point when it comes to comparing this functionality with the desktop app.  When I search for "artist:adele" in Spotify Desktop on Windows, the first five artist results are: Adele, Robyn Adele Anderson, Adele Anthony, Adele Harley and Adèle Anderson.  It's then up to me, as the user, to choose which one I meant.  This is how search generally works, be it Spotify or Google.

> The Spotify app is very good at handling spelling mistakes, such as:
> Ed Sheerun, Ed Sheeron, Ed Shearun etc providing results for "Ed Sheeran"
> The web-api just returns empty results. Is there any way to make it make intelligent / forgiving?
> https://api.spotify.com/v1/search?q=ed+sheerin&type=artist

Again, why is this the web API's job?  Maybe it would be nice to have a search suggestions endpoint to help your users overcome typos, but bear in mind that the "did yu mean?" type data inside the Spotify app is probably generated from tons of analytics data taken from a whole bunch of searches over time.  If I search for a specific string via an API intended for developers, I expect exact results, not that the API will try to correct what I meant.

**Comment by mph070770** [comment] 2016-07-26 15:19
Thanks for your comments. 

I should explain 1 more point - i'm using voice control to select the music - that's why I don't want user interaction (picking from a list etc) and why the spelling can sometimes be incorrect (although Users can also type things incorrectly!).

I've tried the &limit=1 for Adele and it worked - I'll see how I get on with that approach. Thanks for your suggestion.

For the spelling mistakes, I was referring to the mobile app, not the desktop app. I don't know if the functionality is the same. 

If a user makes a spelling mistake (or the speech recogniser) when searching for an artist, this will be passed to the web-api regardless. I could try and correct it programmatically before passing it to the API but I think this would be a significant undertaking. As the Spotify app already provides this, I hoped that the web-api could expose that logic. Perhaps not. However, it is certainly worth asking  the question.

Thanks again.

**Comment by thelinmichael** [comment] 2016-07-28 17:01
Hey @mph070770! The handling of spelling mistakes is captured in #244, so any updates will be posted there. There's however no plans in the short-term to enable this behaviour in the search endpoint.

I agree with the approach @jscholes is suggesting, the top result is the one that Spotify believes is the most likely that you're searching for.

**Comment by thelinmichael** [comment] 2016-07-28 17:04
Closing this issue since it's a duplicate of #244. @mph070770, if you believe that the other issue doesn't capture what you're describing you're very welcome to reopen this one.

**Closed by thelinmichael** 2016-07-28 17:04 UTC

**Comment by technomorph** [comment] 2020-04-03 09:38
Have you tried putting Adele in quotes?
https://api.spotify.com/v1/search?q=“adele”&type=artist
