### ISSUE TITLE
502 Error consistently being returned for /playlists endpoint for some users.

### ISSUE THREAD

**Issue by JasonTBA** [spotify/web-api#876] opened 2018-05-11 21:04 UTC
502 Error consistently being returned for /playlists endpoint for some users. Discovered around May 6th 2018.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists`

#### Scope(s):
* playlist-read-private, playlist-read-collaborative 

#### Steps to reproduce:
1. Try the link below, note user id = "blendedjuice" (you will need to generate an access token). The particular user is necessary to the endpoint failing:
https://beta.developer.spotify.com/console/get-playlists/?user_id=blendedjuice&limit=50&offset=0

#### Expected behaviour:
A response as object as described on `https://beta.developer.spotify.com/documentation/web-api/reference/playlists/get-list-users-playlists/`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by hughrawlinson** [comment] 2018-05-13 09:42
Hey @JasonTBA - I'm unable to reproduce this error. Is it still happening for you?

**Comment by JasonZigelbaum** [comment] 2018-05-13 14:48
Yes it is still happening for some users. Looks like the user I sent you has cleared up (though he is still having consistent issues when the endpoint is being access by our app). I just ran the endpoint again with user "xeeew" and got the following 500 result (see screenshot). Let me know how else I can help. Thanks.

<img width="1334" alt="screen shot 2018-05-11 at 2 02 23 pm" src="https://user-images.githubusercontent.com/821065/39968451-da041572-569a-11e8-8841-1132a19e6880.png">

**Comment by phillipmunn** [comment] 2018-05-13 22:09
We're also seeing potentially the same issue with playlists not loading for some users of the iOS application @Pacemaker. Whilst we cannot confirm at the moment this is the same issue, playlists are not loading for several users with the first reports appearing in the last week.

**Comment by phillipmunn** [comment] 2018-05-13 22:11
Example User: 
https://beta.developer.spotify.com/console/get-playlists/?user_id=Jahnzilla&limit=50&offset=0

**Comment by phillipmunn** [comment] 2018-05-17 17:43
From our own testing unless @hughrawlinson has anything to add - we think this is now fixed. Our affected users now can see their playlists and we haven't seen error 502/500 on this endpoint since.

**Comment by JasonTBA** [comment] 2018-05-17 18:35
I agree on our end as well. The 4-5 users who reported issues have had
their issues resolved. Can't say for certain it's 100% solved but figured
I'd share the info.

**Comment by SolarAaron** [comment] 2018-05-17 18:42
Funny, I just came to report this issue, as I believed I had broken my own account playing with some code.

The web console link would be as follows:
https://beta.developer.spotify.com/console/get-playlists/?user_id=1278527677&limit=50&offset=0

**Comment by arirawr** [comment] 2018-07-23 12:41
Seems like this is resolved! Please reopen if you see this happening again.

**Closed by arirawr** 2018-07-23 12:41 UTC
Labels: bug
