### ISSUE TITLE
Adding follow button to web-page; how do I know if it works? 

### ISSUE THREAD

**Issue by therokkones** [spotify/web-api#1117] opened 2018-12-23 20:29 UTC
Hello, 

I have added a Spotify follow button to the front of my web-page https://www.olarokkones.no/, following the instructions that I found on this link: https://developer.spotify.com/documentation/widgets/generate/follow-button/

Although Spotify has changed their "Follow" with a heart, I believed this button would work - But how do I know if it is working or not? Does it work, or should I use another code to add a Heart-button? Please advice!

All the best, 

Ola

**Comment by bih** [comment] 2018-12-27 15:31
Hello @therokkones,

We haven't changed our follow button with a heart. It should work as intended, and I can confirm that it is working fine for me when I just tested it on your website. I'll close this as this is resolved, you're all set - you shouldn't need to do anything else! :)

**Closed by bih** 2018-12-27 15:31 UTC

**Comment by therokkones** [comment] 2018-12-27 23:15
Thank you so much! :D

Den tor. 27. des. 2018 kl. 16:31 skrev Bilawal Hameed <
notifications@github.com>:
