### ISSUE TITLE
Tracks missing from Recently Played

### ISSUE THREAD

**Issue by Kaprow** [spotify/web-api#666] opened 2017-09-18 19:29 UTC
Issue found on Sept 15 2017.

#### Endpoint(s):
* `GET /v1/me/player/recently-played`

#### Scope(s):
* user-read-recently-played

#### Steps to reproduce:
Obtain list of recently played tracks

#### Expected behaviour:
A record for the last 50 tracks played for more than 30 seconds should be returned

#### Actual behaviour:
Tracks played for their entirety are randomly omitted. I am 99% certain this is happening (via logged behavior) but cannot reproduce consistently since the issue is intermittent. Is anyone else experiencing same/similar issues?

**Comment by Kaprow** [comment] 2017-09-18 19:35
Example: The attached file contains play-history. The same playlist was played from the start (and shuffle = off) on three different days. The second and third track in the playlist are absent from play-history on day 2 and day 3 respectively.

[2017-09-18-071450.txt](https://github.com/spotify/web-api/files/1311932/2017-09-18-071450.txt)

Anyone else seeing this? Am I missing something?

**Comment by Kaprow** [comment] 2017-09-18 19:37
Just noticed song 5 is absent on day 2 as well >.<

**Comment by bih** [comment] 2017-09-21 11:57
Hey! This looks like a bug. When I play songs from the Spotify Desktop App, it does not always show in the recently played even after the track was played in its entirety. We will investigate into this and get back to you.

**Comment by mmontag** [comment] 2017-10-07 18:31
Hi @Kaprow, we've pushed out a potential fix. Can you try again and please let us know if the endpoint is still dropping some songs?

**Comment by Kaprow** [comment] 2017-10-10 15:24
@mmontag @bih Thanks for jumping on this. The issue wasn't consistently reproducible so I can't say with 100% certainty that it's fixed, but I have been monitoring play history since the push and it looks accurate so far. Can you describe the fix so I can try some targeted test cases? Thanks!

**Comment by bih** [comment] 2017-10-10 16:23
@Kaprow I don't think there's a way to actually test from your codebase given the nature of this bug. There may be some targeted test cases that @mmontag might have, but otherwise I know it's something we're aware of and will continue to keep an eye on.

We'd love to hear if you're still seeing any tracks missing from the endpoint. Cheers!

**Comment by mmontag** [comment] 2017-10-10 20:54
@Kaprow sure. A small percentage of events were being dropped at random, during peak hours, so there is no simple reproduction step. The fix was in our event delivery infrastructure, not the Web API or desktop client.

**Comment by Kaprow** [comment] 2017-10-10 20:57
Thanks Mark, that helps. What do you consider to be "peak hours"? I'll try some testing during those times.

Appreciated, thanks!

On Oct 10, 2017, at 1:55 PM, Matt Montag <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kaprow<https://github.com/kaprow> sure. A small percentage of events were being dropped at random, during peak hours, so there is no simple reproduction step. The fix was in our event delivery infrastructure, not the Web API or desktop client.

**Comment by Kaprow** [comment] 2017-10-10 20:58
Sorry, Matt, not Mark! :D

**Comment by Kaprow** [comment] 2017-10-19 20:55
Matt,


I've been performing some tests. Play history from my mobile seems fine but the desktop client (Win 10 Pro) does not work at all. Nothing comes through the API when playback is initiated from the desktop client.


Thanks

-r

________________________________

**Comment by Kaprow** [comment] 2017-10-19 21:15
@bih @mmontag Just FYI, my desktop client was still dropping songs (all of them, actually) however completely uninstalling and re-installing the desktop client appears to have fixed the issue. Seems odd since the fix was implemented in your message delivery service and not in the client. iOS client seems to be working just fine.

Thanks!

**Comment by mmontag** [comment] 2017-10-23 19:35
@Kaprow Can't be sure now but the desktop missing songs might have been due to "private listening" mode, which is a client-side setting. I think we're okay to close this issue for now - we've been monitoring it internally and have seen zero missing events.

**Closed** 2017-10-28 14:14 UTC
Labels: bug
