### ISSUE TITLE
Server 500 error on endpoint - /v1/me/player

### ISSUE THREAD

**Issue by thordavid** [spotify/web-api#747] opened 2017-12-21 10:37 UTC
Issue found on December 20th 2017.

#### Endpoint(s):
* `PUT  Server 500 error on endpoint - /v1/me/player`

#### Scope(s):
* 
#### Steps to reproduce:
1. call endpoint with existing valid device id
2. receive 500 error
3. go to any spotify app and start playback on any device ( does not need to be the one that is the target of the previous call ) 
4. run same command against same endpoint and id from step 1 and it works fine

#### Expected behaviour:
To be able to startplayback on a valid device even if there is not active spotify playback going on 

#### Actual behaviour:
500 Server Error (consistently)

**Comment by mbellgb** [comment] 2017-12-29 11:47
I'm running into the same issue when requesting playback on a valid `device_id` (created with the web playback API) when there's no music playing on any of the user's devices. The endpoint does work however if I start playback on another device and then try the request again.

I can reproduce with my [test project](https://github.com/mbellgb/jukeify). Notable code blocks are linked below:

[/player API call](https://github.com/mbellgb/jukeify/blob/25739f35110d2371e5a1947d6eef284b74fc9815/app/src/containers/pages/PlayerPage.jsx#L90)

[function call is made when the player returns a "ready" event](https://github.com/mbellgb/jukeify/blob/25739f35110d2371e5a1947d6eef284b74fc9815/app/src/containers/pages/PlayerPage.jsx#L122)

[player is set up when the spotify object is loaded in the window](https://github.com/mbellgb/jukeify/blob/25739f35110d2371e5a1947d6eef284b74fc9815/app/src/containers/pages/PlayerPage.jsx#L142)

[...which is set with the onSpotifyWebPlaybackSDKReady method here](https://github.com/mbellgb/jukeify/blob/25739f35110d2371e5a1947d6eef284b74fc9815/app/public/index.html#L41)

**Comment by sevi-l** [comment] 2017-12-31 03:23
i have the exact same problem

**Comment by Bart1909** [comment] 2018-01-02 18:21
I have also the same problem. 
I could not determine if it depends on the is_active flag of the device.
Sometimes I get a 500 error when using 
https://api.spotify.com/v1/me/player/play?device_id=
or
https://api.spotify.com/v1/me/player/repeat?state=off&device_id=
or 
https://api.spotify.com/v1/me/player/shuffle?state=false&device_id=

And sometime the error occurs on is_active = false devices and sometimes on is_active = true devices. 

The device ID is retrieved before via https://api.spotify.com/v1/me/player/devices so it should be correct.

**Comment by Bart1909** [comment] 2018-01-18 16:59
Any update on this?

**Comment by n-tin** [comment] 2018-01-26 20:50
For me the problem seemed to occur if no device had been activated before (is_active:false for all devices).

What worked for me: PUT `https://api.spotify.com/v1/me/player/play?device_id=PUT_YOUR_DEVICE_ID_HERE`
Hint: include the GET parameter "device_id".
See: https://developer.spotify.com/web-api/start-a-users-playback/

**Comment by Bart1909** [comment] 2018-01-29 17:21
Hi @n-tin,

I do the following:

- Getting the Userdevices via https://api.spotify.com/v1/me/player/devices
- Transfer the Playback to the device as described in https://developer.spotify.com/web-api/transfer-a-users-playback/
- Disable Shuffle on this device (https://developer.spotify.com/web-api/toggle-shuffle-for-users-playback/)
- Disable Repeat on this device (https://developer.spotify.com/web-api/set-repeat-mode-on-users-playback/)
- Start the Playback on this device

In most times, If I got a 500, I got it while transferring the playback, setting shuffle/repeat mode and starting the playback. But not for every user. And not only at specific times.

So for example at 7:01 I got an error for user A, at 7:02 it works fine for user B, at 7:03 I got an error for user C. Later it works fine for user A and I got an error for user B.

**Comment by marante** [comment] 2018-02-05 13:08
Hi, I can confirm that this is still an issue. If I start Spotify on my laptop and don't start a song, the playback doesn't work. What I have to do is manually start and pause a song, and then it works. It seems that devices that are in "sleep mode", can't be accessed until a song has been played manually. This is some what cumbersome, because you have to do some ugly code to circumvent it. I.E play/stop immediately when the program starts, and then run the code.

**Comment by platelminto** [comment] 2018-04-07 14:16
I also still get this issue, but only with the start/resume playback method. I've tried with the default `player/play` method, and also providing it with a device id, but I always get a 502 error with an error message 'Backend respond with 500'.

**Comment by eddietindame** [comment] 2018-11-12 13:48
This issue still occurs for me.

Trying to transfer playback to a device created using the Spotify Web Playback SDK when no previous devices were active. I get 500 error. Then it works as soon as I try it with another device open (even if I close the secondary device right away). Are there any plans to resolve this?

**Comment by kerorojason** [comment] 2019-05-22 05:21
I'm also facing the same problem with "/v1/me/player/play" no matter the device is active or not...
But sometimes it works fine. Is this Spotify server's problem?

**Comment by mwong678** [comment] 2019-07-29 08:04
I think it depends how how I've had spotify open on the device that affects its performance

So when I call /v1/me/player/play with a valid device(not active), that i basically turned the app on the phone and then exited out almost immediately, it will submit the play, but not play immediately. It will however, start playing when I open the app. 

However, if i've been listening to spotify for a while(at least a few minutes) and then exit the app and then make the api call, the call should be fine(spotify marks the device as active even though i exited the app already)

**Closed** 2020-03-01 15:00 UTC
Labels: bug
